### ISSUE TITLE
Option to use latest zulip git?

### ISSUE THREAD

**Issue by carlokok** [zulip/docker-zulip#102]
Would it be possible to have an option to use latest git of zulip instead of a specific release?

**Comment by galexrt** [comment]
@carlokok Not really right now. The image is built from a release tarball, see https://github.com/galexrt/docker-zulip/blob/master/Dockerfile#L19.

I would be okay with taking a PR to add a second Dockerfile for building from Zulip repository branch/tag. :)

**Comment by timabbott** [comment]
I think it's reasonable to just have it always use a branch/tag, now that the Zulip installer runs happily from that context.  I bet we'll have this fixed by the end of the day at the PyCon sprints.

**Comment by carlokok** [comment]
I've got a fork that does this (from master currently) see https://github.com/carlokok/docker-zulip
