### ISSUE TITLE
LDAP works with manage.py query_ldap but login does not.

### ISSUE THREAD

**Issue by razem-io** [zulip/docker-zulip#119]
Hi,

thank you for dockerizing zulip! We have a community project in Germany where I try to set this up. I managed to get LDAP working somehow.

```
./manage.py query_ldap username
email: ['mail@******.domain']
first_name: ['user']
last_name: ['name']
```

The Login however does not. We have the following settings in our docker-compose.yml:

```
      ZULIP_AUTH_BACKENDS: "ZulipLDAPAuthBackend"
      SETTING_AUTH_LDAP_SERVER_URI: "ldap://ldap"
      SETTING_AUTH_LDAP_BIND_DN: "cn=admin,dc=domain,dc=ending"
      SECRETS_auth_ldap_bind_password: "topsecret"
      SETTING_AUTH_LDAP_USER_SEARCH: 'LDAPSearch("ou=users,dc=domain,dc=ending", ldap.SCOPE_SUBTREE, "(uid=%(user)s)")'
      SETTING_LDAP_APPEND_DOMAIN: None
      SETTING_LDAP_EMAIL_ATTR: "mail"
      SETTING_AUTH_LDAP_USER_ATTR_MAP: '{ "first_name": "givenName", "last_name": "sn", "email": "mail" }'
```
I can't find any logs where an error gets posted. Can somebody help us? Thank you very much!

**Comment by timabbott** [comment]
What gets logged in `/var/log/zulip/server.log` when you try to login?

**Comment by razem-io** [comment]
It has the following log output:

```
2018-05-27 08:47:30.023 INFO [zr] 192.168.1.1     GET     302  83ms (+start: 840ms) / (unauth via ?)
2018-05-27 08:47:31.042 INFO [zr] 192.168.1.1     GET     200 208ms (db: 4ms/3q) (+start: 794ms) /login/ (unauth via ?)
2018-05-27 08:47:32.046 INFO [] Tornado   0.0% busy over the past 60.0 seconds
2018-05-27 08:47:32.244 INFO [zr] 192.168.1.1     GET     404 945ms (db: 4ms/2q) /django_static_404.html (unauth via ?)
2018-05-27 08:47:36.625 INFO [zr] 192.168.1.1     POST    200 258ms (db: 5ms/4q) (+start: 837ms) /accounts/login/ (unauth via ?)
2018-05-27 08:47:36.756 INFO [zr] 192.168.1.1     GET     404  25ms (db: 2ms/2q) /django_static_404.html (unauth via ?)
```

**Comment by razem-io** [comment]
I also tried saving passwords in a different hash format (md5, sha, ssha). Sadly this did not do the trick. I was also syncing ldap accounts between the format changes to make sure it has the correct information.

**Comment by timabbott** [comment]
What are you entering in the login form?  I believe with that configuration, users should be entering their LDAP username and password.

The other thing you can check is what you ended up with at the bottom of `/etc/zulip/settings.py` -- it's possible the LDAP backend configuration isn't going through correctly.

**Comment by timabbott** [comment]
(Also, did you create an organization before trying to use LDAP?  You have to use EmailAuthBackend for organization creation)

**Comment by razem-io** [comment]
Thank you for your suggestions! I will try that as soon as I have the time and report back here.

**Comment by razem-io** [comment]
Your aducated guess was right. I forgot to create an organization before using LDAP. Everything work flawless now. Thank you so much!
