### ISSUE TITLE
The image seems to append to settings.py every time it's started

### ISSUE THREAD

**Issue by zingmars** [zulip/docker-zulip#130]
Seems to happen in https://github.com/zulip/docker-zulip/blob/master/entrypoint.sh#L138 

If you either have the data directory mounted, or if you exec `docker exec -it zulip_zulip_1 bash` into the running container, reading the /etc/zulip/settings.py reveals that the settings from the docker-compose (and I assume the docker command) are appended to the file every time the container is run. Not only this bloats the file for no reason, I feel like it might have negative effects when someone wants to actually remove a configuration option.

**Comment by gioragutt** [comment]
@zingmars does it do the same if you do `docker-compose exec zulip /bin/bash`?

**Comment by zingmars** [comment]
Nope, it only happens when I'm starting up the container.

**Comment by gioragutt** [comment]
So let me get it right, you're complaining about the fact that the settings from `docker-compose.yml` get copied to `settings.py` in the first place, or that they're copied there more than once?

**Comment by zingmars** [comment]
The latter option. If I was to remove an option from `docker-compose.yml` I would also have to go and manually delete it from settings.py (and/or, since there's now probably a dozen entries of that setting, probably clean it as well) because it would be present there after restarting the container.

**Comment by timabbott** [comment]
This is definitely a bug.  I think the non-`MANUAL_CONFIGURATION` configuration management code, when it's editing `settings.py`, should start by making a fresh copy of `zproject/prod_settings_template.py` (and then appending the lines on top of that).  That way, the `settings.py` configuration will always be consistent with what's in the environment (which feels like it's the user intent here).

@galexrt @gioragutt what do you think?

**Comment by gioragutt** [comment]
@timabbott that seems right. Considering this always starts as the template file, this seems right to "restart" with the template each time.
