### ISSUE TITLE
zulip-thumbor entered FATAL state

### ISSUE THREAD

**Issue by fradee** [zulip/docker-zulip#153]
When I've updated from 1.9.0-rc1 to 1.9.0-rc1-2 and restart services - got an error with zulip-thumbor. 

> 2018-08-28 09:08:55,122 INFO success: zulip_events_digest_emails entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2018-08-28 09:08:55,122 INFO success: zulip_events_email_senders entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2018-08-28 09:08:55,122 INFO success: zulip_deliver_scheduled_messages entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2018-08-28 09:08:56,124 INFO spawned: 'zulip-thumbor' with pid 136
> 2018-08-28 09:08:57,126 INFO success: zulip-thumbor entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2018-08-28 09:08:57,217 INFO exited: zulip-thumbor (exit status 1; not expected)
> 2018-08-28 09:08:58,219 INFO spawned: 'zulip-thumbor' with pid 215
> 2018-08-28 09:08:59,169 INFO exited: zulip-thumbor (exit status 1; not expected)
> 2018-08-28 09:09:00,889 INFO spawned: 'zulip-thumbor' with pid 222
> 2018-08-28 09:09:01,838 INFO exited: zulip-thumbor (exit status 1; not expected)
> 2018-08-28 09:09:04,378 INFO spawned: 'zulip-thumbor' with pid 223
> 2018-08-28 09:09:04,499 INFO exited: zulip-thumbor (exit status 1; not expected)
> 2018-08-28 09:09:07,501 INFO spawned: 'zulip-thumbor' with pid 224
> 2018-08-28 09:09:07,620 INFO exited: zulip-thumbor (exit status 1; not expected)
> 2018-08-28 09:09:08,114 INFO gave up: zulip-thumbor entered FATAL state, too many start retries too quickly

**Comment by fradee** [comment]
In /var/log/zulip/thumbor.log error with S3_AUTH_UPLOADS_BUCKET but I have not use S3 or AWS Api

> root@93762d2e48b0:/var/log/zulip# cat thumbor.log
Traceback (most recent call last):
  File "/home/zulip/deployments/current/zulip-thumbor-venv/bin/thumbor", line 11, in <module>
    sys.exit(main())
  File "/srv/zulip-venv-cache/890ced270adac8406802ba25797517e3250e67d8/zulip-thumbor-venv/local/lib/python2.7/site-packages/thumbor/server.py", line 136, in main
    config = get_config(server_parameters.config_path, server_parameters.use_environment)
  File "/srv/zulip-venv-cache/890ced270adac8406802ba25797517e3250e67d8/zulip-thumbor-venv/local/lib/python2.7/site-packages/thumbor/server.py", line 53, in get_config
    return Config.load(config_path, conf_name='thumbor.conf', lookup_paths=lookup_paths)
  File "/srv/zulip-venv-cache/890ced270adac8406802ba25797517e3250e67d8/zulip-thumbor-venv/local/lib/python2.7/site-packages/derpconf/config.py", line 75, in load
    return cls.__load_from_path(conf, path)
  File "/srv/zulip-venv-cache/890ced270adac8406802ba25797517e3250e67d8/zulip-thumbor-venv/local/lib/python2.7/site-packages/derpconf/config.py", line 95, in __load_from_path
    six.exec_(code, module.__dict__)
  File "/srv/zulip-venv-cache/890ced270adac8406802ba25797517e3250e67d8/zulip-thumbor-venv/local/lib/python2.7/site-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "<string>", line 660, in <module>
ImportError: cannot import name S3_AUTH_UPLOADS_BUCKET
...

**Comment by timabbott** [comment]
@sampritipanda @adnrs96 any ideas?  Thumbor isn't actually used by default in production yet, so this is probably not an immediate user-facing problem, but we should definitely fix this soon.

I think the root problem here is probably that `LOCAL_UPLOADS_DIR` isn't being detected in `zthumbor/thumbor.conf`, which may, in turn, be an issue with how `sys.path` is setup for the thumbor process...

**Comment by fradee** [comment]
fixed by adding environment setting **SETTING_LOCAL_UPLOADS_DIR: "/home/zulip/uploads"** for zulip service into docker-compoe.yml

**Comment by timabbott** [comment]
Hmm, I wonder if the root issue here is that we're not using the initial values from `prod_settings_template.py` in generating the settings file for the Docker image...

**Comment by timabbott** [comment]
@fradee I just posted 1.9.0-rc2-0; can you confirm that resolves this issue for you?

**Comment by fradee** [comment]
@timabbott, confirm - the issue with zulip-thumbor was fixed in 1.9.0-rc2-0
