### ISSUE TITLE
Permission denied errors when executing docker-compose up in Mac OS X

### ISSUE THREAD

**Issue by theccalderon** [zulip/docker-zulip#158]
Hi,

I'm trying to run Zulip with docker-compose however, anytime I run docker-compose up I see the following errors:

$ docker-compose up                                                                                                                                                               

> Starting docker-zulip_zulip_1 ...
> Starting docker-zulip_redis_1 ...
> Starting docker-zulip_zulip_1    ... done
> Starting docker-zulip_redis_1    ... done
> Starting docker-zulip_database_1 ... done
> Attaching to docker-zulip_rabbitmq_1, docker-zulip_memcached_1, docker-zulip_zulip_1, docker-zulip_database_1, docker-zulip_redis_1
> database_1   | chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted
> zulip_1      | === Begin Initial Configuration Phase ===
> redis_1      | chmod: changing permissions of '/var/lib/redis': Operation not permitted
> zulip_1      | mkdir: cannot create directory ‘/data/backups’: Permission denied
> zulip_1      | mkdir: cannot create directory ‘/data/certs’: Permission denied
> zulip_1      | mkdir: cannot create directory ‘/data/uploads’: Permission denied
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> rabbitmq_1   | chown: changing ownership of '/var/lib/rabbitmq': Operation not permitted
> docker-zulip_zulip_1 exited with code 1
> docker-zulip_database_1 exited with code 1
> docker-zulip_redis_1 exited with code 1
> docker-zulip_rabbitmq_1 exited with code 1

I'm running macOS High Sierra and my Docker version is Docker version 18.06.1-ce, build e68fc7a.

Any help is appreciated. Thanks!

**Comment by timabbott** [comment]
I think you need to give the current user permission to write to `/opt/docker` (aka the mount points shared with the Docker container).

**Comment by ccalderon911217** [comment]
Executed 

> sudo chmod 777 /opt/docker

but getting the same error.

**Comment by galexrt** [comment]
It seems that the Docker `osxfs` storage driver on Mac is probably causing the problem, see https://stackoverflow.com/a/43213455.

**Comment by tamhv** [comment]
did you add /opt/docker to Docker preferences > Fire sharing ?

**Comment by QuantumInformation** [comment]
I just used sudo for the mac, kinda sad.

**Comment by Jorchava** [comment]
years after but yeah got similar problems "mkdir Operation not permitted" , MacOS Catalina 10.15.7 and I had to go in /docker directory and :
`sudo chmod 777 .`
To the entire docker directory

**Comment by i-ky** [comment]
I guess #307 should fix this issue.

**Comment by dbulaj** [comment]
@Jorchava 

> years after but yeah got similar problems "mkdir Operation not permitted" , MacOS Catalina 10.15.7 and I had to go in /docker directory and : `sudo chmod 777 .` To the entire docker directory

where do you have this `/docker` directory, I've looked in several places and can't find it anywhere :( And I got exact same issue 

`mkdir /host_mnt/****: operation not permitted`

**Comment by timabbott** [comment]
This was likely fixed through the transition to using Docker storage volumes a couple years ago.
