### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by zegervdv** [zulip/docker-zulip#159]
When I visit zulip after clean `docker-compose up` I get an Internal Server Error page.

I've searched through the logs in `/var/log/zulip` but cannot find any error indication.
The only thing I've found was the following in `/var/log/nginx/error.log`:
```
2018/09/13 18:08:31 [error] 106#106: *1 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 10.150.30.229, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/home/zulip/deployments/uwsgi-socket:", host: "localhost"
```

I'm using `1.9.0-rc2-0`.
Is there any place I can look for more information on the error?

**Comment by timabbott** [comment]
/var/log/zulip/errors.log is the place to look.

**Comment by zegervdv** [comment]
I’ve checked that one and it was empty.

**Comment by zegervdv** [comment]
It seems to work correctly when I'm directly in the same network of the zulip server, but when connecting via VPN it throws the 500.
Maybe something times out too soon?

**Comment by timabbott** [comment]
I see, so the issue is happening at the `nginx` layer.  I'd consult the documentation/support for your VPN and interactions with webservers like `nginx`; I suppose it's possible the VPN has a misconfigured timeout, but it'd have to be very short to 500 on the first request... more likely, your VPN is instantly timing out requests to whatever host Docker is running on?

**Comment by zegervdv** [comment]
I have set up traefik on that machine as a reverse proxy in front of Zulip and it seems to be working fine now. 

I’m not sure why it’s not working directly but using traefik was the intention anyway. 

Sorry to bother you about it.

**Comment by gkoerk** [comment]
> I have set up traefik on that machine as a reverse proxy in front of Zulip and it seems to be working fine now.
> 
> I’m not sure why it’s not working directly but using traefik was the intention anyway.
> 
> Sorry to bother you about it.

How did you get this working?

**Comment by timabbott** [comment]
@gkoerk https://zulip.readthedocs.io/en/latest/production/deployment.html#putting-the-zulip-application-behind-a-reverse-proxy is hopefully helpful documentation on what Zulip expects?
