### ISSUE TITLE
Mounts Denied Issue Starting Docker Compose

### ISSUE THREAD

**Issue by scottilee** [zulip/docker-zulip#162]
I am running Docker Version 18.03.1-ce-mac65 (24312) on MacOS Sierra 10.13.6. Cloning https://github.com/zulip/docker-zulip and running `docker-compose pull`, then `docker-compose up` results in the following errors:

```
$ docker-compose up
Starting docker-zulip_redis_1 ...
docker-zulip_rabbitmq_1 is up-to-date
Starting docker-zulip_zulip_1 ...
Starting docker-zulip_zulip_1    ... error
docker-zulip_memcached_1 is up-to-date
Starting docker-zulip_redis_1    ... error
ERROR: for docker-zulip_zulip_1  Cannot start service zulip: b'Mounts denied: \r\nThe path /opt/docker/zulip/zulip\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'

ERROR: for docker-zulip_redis_1  Cannot start service redis: b'Mounts denied: \r\nThe path /opt/docker/zulip/redis\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shaStarting docker-zulip_database_1 ... error

ERROR: for docker-zulip_database_1  Cannot start service database: b'Mounts denied: \r\nThe path /opt/docker/zulip/postgresql/data\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'

ERROR: for zulip  Cannot start service zulip: b'Mounts denied: \r\nThe path /opt/docker/zulip/zulip\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths fromDocker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'

ERROR: for redis  Cannot start service redis: b'Mounts denied: \r\nThe path /opt/docker/zulip/redis\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths fromDocker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'

ERROR: for database  Cannot start service database: b'Mounts denied: \r\nThe path /opt/docker/zulip/postgresql/data\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'
ERROR: Encountered errors while bringing up the project.
```

https://stackoverflow.com/questions/45122459/docker-mounts-denied-the-paths-are-not-shared-from-os-x-and-are-not-known seems to explain the issue but is anyone else having this issue?

Going to `File Sharing` under Docker Preferences and adding those directories (/opt/docker/zulip/{zulip,redis,postgresql}) does not fix the issue.

**Comment by timabbott** [comment]
Try just replacing the `/opt/docker/zulip` paths with something under your home directory in the `docker-compose.yml` and see if that helps?  

We should also look at what other projects that need a database (e.g. GitLab) do for this.

**Comment by nvnt16** [comment]
@scottilee Were you able to resolve this?

**Comment by aneelx64** [comment]
I'm having the same issue. There seems to be no real answer anywhere.

**Comment by johnnashautomation** [comment]
My issue fixed when I removed the project Path from File Sharing in docker preferences and restart the docker,
Then add the project file path again.

Hope this helps someone

**Comment by eghan** [comment]
worked for me thanks @johnnashautomation

**Comment by elgandoz** [comment]
I just had to add the path `/opt/docker/zulip` in Preferences > Resources > File sharing and everything run smoothly after that.
<img width="1382" alt="Screen Shot 2021-09-11 at 5 43 13 pm" src="https://user-images.githubusercontent.com/5859926/132940805-9e760548-7121-490f-b0fd-9552ad58bafc.png">

It seems required since it reappears if I remove the path.
Running Docker 4.0.0 on MacOS BigSur 11.5.2 .
