### ISSUE TITLE
Add Zulip Server 1.9.1

### ISSUE THREAD

**Issue by Hybr13** [zulip/docker-zulip#183]
Please update this repository with the latest Zulip release.
I want to customize notification sounds (:

**Comment by ajkerzner** [comment]
I second this. Any plans for the upgrade to the latest stable of Zulip?

**Comment by timabbott** [comment]
We should upgrade this project to 2.0 this week when we release Zulip 2.0.

**Comment by ajkerzner** [comment]
Oh, nice. I look forward to v2, Tim !

**Comment by luckyraul** [comment]
@timabbott 2.0 is released, but in then docker hub still 1.9.0

**Comment by timabbott** [comment]
It appears that Docker Hub stopped automatically building this project a month or two ago without warning. 
 I just re-enabled that configuration and re-pushed the 2.0.0 tag; hopefully that will build properly.

**Comment by timabbott** [comment]
(Thanks for the report @luckyraul, as I had believed the release was already up on DockerHub).

**Comment by luckyraul** [comment]
@timabbott  No autobuilds available on repository

**Comment by timabbott** [comment]
@luckyraul check now -- DockerHub is slow so the builds take 45 minutes to run.

**Comment by luckyraul** [comment]
@timabbott 1 build available - for the lastest tag, no 2.0.0

**Comment by luckyraul** [comment]
@timabbott no 2.0.1 still

**Comment by timabbott** [comment]
I just released 2.0.1.  I'll also update our release checklist so that we do this as part of Zulip server releases.
