### ISSUE TITLE
Remote Postgres RDS tsearch_data error

### ISSUE THREAD

**Issue by rap999a** [zulip/docker-zulip#193]
I am trying to install zulip with a remote RDS instance. When I try to migrate the database I am getting the following error.

`django.db.utils.InternalError: could not open dictionary file "/rdsdbbin/postgres-9.6.12.R1/share/tsearch_data/en_us.dict": No such file or directory`

I read #92 and found that it needs tsearch module installed. I checked the parameter group of the RDS it has tsearch2 installed still the installation is failing. Is it really possible to run zulip with an RDS instance. If so will you guide me how?

**Comment by timabbott** [comment]
You need the `tsearch_extras` module, which is not available with RDS.
