### ISSUE TITLE
fixed pass env 

### ISSUE THREAD

**Issue by komp24** [zulip/docker-zulip#194]
in section Troubleshooting
_"A new Zulip setting not being passed through the Docker entrypoint.sh script properly. If you run into this sort of problem you can work around it by specifying a ZULIP_CUSTOM_SETTINGS with one setting per line below, but please report an issue so that we can fix this for everyone else._"

entrypoint.sh work if we build Dockerfile, if we use "docker-compose up" and prebuild image from dockerhub, in docker-compose.yml add new setting for example in scheme: SETTING_XX: 'yy'

**Comment by timabbott** [comment]
I don't understand the issue -- can you explain it?
