### ISSUE TITLE
Error email_mirror - Missing recipient in mirror email

### ISSUE THREAD

**Issue by rlagutinhub** [zulip/docker-zulip#196]
I configured email_mirror via imap (becouse postfix not installed on docker-zulip),
 email_mirror executed successfully but with
exception via raise **Missing recipient in mirror email**

```cat /var/log/zulip/errors.log```
![123](https://user-images.githubusercontent.com/30324030/57155892-48555100-6de5-11e9-8866-dc5872b96528.png)

https://github.com/zulip/zulip/blob/b570c0dafa9cd8cf7d4b2af51c5cc8496197f405/zerver/lib/email_mirror.py#L318

how much this error is critical?
and additional plz add support imap without using ssl)

**Comment by timabbott** [comment]
How are you testing?  I think that error is what happens when you send an email into the email mirror that isn't to an email address matching the configured email address pattern.

**Comment by rlagutinhub** [comment]
> How are you testing? I think that error is what happens when you send an email into the email mirror that isn't to an email address matching the configured email address pattern.

I was wrong because i used streams mail aliases on mailbox  what configured for ZULIP_ADMINISTRATOR (SETTING_ZULIP_ADMINISTRATOR).
other messages in this mailbox ZULIP_ADMINISTRATOR cause this error (because not parsed headers mail).
now after setting unused mailbox with mail aliases for my streams i don't get new errors
