### ISSUE TITLE
Internal Server Error (500) during registration process for new user.

### ISSUE THREAD

**Issue by Petaris** [zulip/docker-zulip#198]
After starting the docker images with docker-compose up I am able to create an organization and register the first admin user.  Any user after that who uses a generated invite link gets an Internal Server Error (500).

**Comment by timabbott** [comment]
@Petaris there's lots of configuration issues that could cause this.  You need to look at `/var/lob/zulip/errors.log` inside the container to see what's wrong.

**Comment by t3hmrman** [comment]
@Petaris when this happened to you, were the users able to log in *despite* the 500 error?

**Comment by bayareacoder** [comment]
I have the same issue: entering email address for a new user signup from the page generated by invite link shows '500 internal server error'. There is no file /var/log/zulip/errors.log on the server. Using Digital Ocean 1-click Droplet install.

**Comment by bayareacoder** [comment]
I had the same issue and after inspecting the errors.log file it was because the tokenized reply email address was apparently not set correctly. I had set it to the format shown in the example:
```
# The noreply address to be used as the sender for certain generated
# emails.  Messages sent to this address could contain sensitive user
# data and should not be delivered anywhere.  The default is
# e.g. noreply-{random_token}@zulip.example.com (if EXTERNAL_HOST is
# zulip.example.com).  There are potential security issues if you set
# ADD_TOKENS_TO_NOREPLY_ADDRESS=False to remove the token; see
# https://zulip.readthedocs.io/en/latest/production/email.html for details.
ADD_TOKENS_TO_NOREPLY_ADDRESS = True
TOKENIZED_NOREPLY_EMAIL_ADDRESS = 'noreply-{random_token}@<domain>'
```
However it should be set to:
```
TOKENIZED_NOREPLY_EMAIL_ADDRESS = 'noreply-{token}@<domain>'
```

I suggest to update the comment.

**Comment by timabbott** [comment]
@bayareacoder thanks for the report of that issue!  We've merged a fix to that comment in `zulip/zulip` master.  

I think it's likely the original poster had a different issue, but they seem to not have posted any error logs details that will tell us what it was, so I'm going to close this issue as having resolved at least one 500.

**Comment by bayareacoder** [comment]
Thank for follow-up. We just starting using Zulip (on DigitalOcean, with emails connected to Mailgun) and I have to say kudos for writing a great product
