### ISSUE TITLE
Permission denied while starting container

### ISSUE THREAD

**Issue by dalanmiller** [zulip/docker-zulip#211]
Container fails out the gate when trying to create a symlink for the `/etc/letsencrypt` folder. I've checked and the permissions on the folder are actually `777`'d 
```
zulip/zulip$ ls -alh
total 24K
drwxrwxrwx 6 nobody 4294967294 4.0K Jul 28 00:53 .
drwxrwxrwx 6 nobody 4294967294 4.0K Jul 28 00:45 ..
drwxrwxrwx 2 nobody 4294967294 4.0K Jul 28 00:53 backups
drwxrwxrwx 2 nobody 4294967294 4.0K Jul 28 00:53 certs
drwxrwxrwx 2 nobody 4294967294 4.0K Jul 28 00:53 letsencrypt
drwxrwxrwx 2 nobody 4294967294 4.0K Jul 28 00:53 uploads
```

I've also set the user for the container to match that of a user with permissions on the docker host. 

Here's the container output when starting up:
```
Attaching to docker_zulip_1
zulip_1                 | === Begin Initial Configuration Phase ===
zulip_1                 | ln: failed to create symbolic link '/etc/letsencrypt': Permission denied
docker_zulip_1 exited with code 1
```

**Comment by timabbott** [comment]
What host OS is this on?  I find this a bit surprising because that directory should be entirely within the guest, so the problem my be that your OS isn't allowing the guest to create symbolic links at all.

**Comment by dalanmiller** [comment]
Hey @timabbott this is on Ubuntu 18.04. After inspecting further, I think the issue that is happening is that the volume being mounted into container is an NFS mount on the host. Something in the uid or guid isn't lining up though as the volume on the host is showing 'nobody' as the owning user. 😵

**Comment by dalanmiller** [comment]
Solved! Needed to fix NFS user permissions and then recreate the directories being mounted into Zulip
