### ISSUE TITLE
Problem with crudini with custom CA in docker-compose

### ISSUE THREAD

**Issue by flavienbwk** [zulip/docker-zulip#217]
Hello,

When launching docker-compose, I get the following error :

![image](https://user-images.githubusercontent.com/14158127/66705501-c2d8b400-ed27-11e9-943f-dec00f4c749d.png)

I clarify that I use the "custom CA" option of the docker-compose file when running it.

Where does the problem come from ?

Thanks,

**Comment by timabbott** [comment]
The `crudini` package is installed by the Zulip installer, so I'm a little surprised you're seeing this issue.  Can you paste a more complete traceback showing when this happens in the run?  Maybe there's an ordering issue with when that gets installed.

**Comment by flavienbwk** [comment]
Thank you. 
I've moved to another project. I close the issue.
