### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by aiveras** [zulip/docker-zulip#221]
As far as I can see there is a new release for 2.0.6. When will this be integrated?

**Comment by timabbott** [comment]
It's quick to do, but there's also little benefit for 2.0.6 as the primary changes don't benefit it.  I'll just take care of it now.

**Comment by wandhydrant** [comment]
Something might be missing:
```
# docker pull zulip/docker-zulip:2.0.6-0
Error response from daemon: manifest for zulip/docker-zulip:2.0.6-0 not found
```
2.0.5-0 downloads well.

**Comment by andersk** [comment]
It had been tagged as `zulip/docker-zulip:latest` and not `zulip/docker-zulip:2.0.6-0`. I’ve added the missing tag.
