### ISSUE TITLE
#220 PR Incoming Mail to Stream (need help)

### ISSUE THREAD

**Issue by denis-ev** [zulip/docker-zulip#222]
I'm trying to get the incoming Mail in Zulip working.
Right now Postfix needs to be startet with `postfix start`, but when it's startet
I can `telnet {hostname} 25` and see the Zulip Postfix Message, but an incoming mail to a stream gets rejected.

I'd like to have this feature working, but not enought time to look into it right now.
Maybe someone else has an idea, PR #220.

**Comment by timabbott** [comment]
Closing in favor of #348, which has more discussion of the same problem.
