### ISSUE TITLE
Messages not sending after a while, possibly queue worker related

### ISSUE THREAD

**Issue by t3hmrman** [zulip/docker-zulip#225]
I'm finding that after zulip is running for a while messages are not actually sending -- they *look* sent in the web client, and websocket activity happens (an ACK comes back), but if you reload the message is not persisted/present.

My guess is that the rabbitmq workers are failing and not restarting. I think this because it happens to more than just messages -- invitation emails also do not get sent as well when it's in this state. Once I *restart* the zulip instance (only `zulip`, not memcached/postgres/rabbitmq/redis), the messages/emails start flowing again.

Looking at the websocket traffic I *do* see the message go, and an ACK come back. I haven't done enough research but I can only assume that tornado is handling the websocket traffic, putting something on the `message_sender` queue (and other queues), and it's just not getting handled?

If I check in `/var/log/zulip/workers.log` I don't see any errors, and I see lots of initial worker connections (and specifically see 3 workers connect to `message_sender` queue) and one or two warnings.

**Comment by t3hmrman** [comment]
This ticket *might* be better suited for the regular zulip repo but I put it here since it's running in a containerized environment (k8s to be specific)

**Comment by t3hmrman** [comment]
An update -- the messages I sent 2 days ago *just* showed up (logged in from a different computer), the UI says they were sent today @ 3:00PM. It *doesn't* correspond with a server restart, because the last restart was 7 days ago.

**Comment by timabbott** [comment]
Given you're using k8s, it's possible this is fixed in zulip/zulip#10776.  Can you try running Zulip 2.1-rc1 to see if it's fixed for you?

**Comment by t3hmrman** [comment]
Hey @timabbott I'm running the released `zulip/docker-zulip` versions -- the most recent released version I see is `2.0.7-0`, I assume the `-rc` images don't get released?

**Comment by timabbott** [comment]
Yeah, you can build your own as documented in this project.  Though 2.1.0 should be out in the next 24 hours in any case.

**Comment by t3hmrman** [comment]
An update -- I recently re-installed Zulip with `2.1.1-0`, going to be testing the chat over the next few days.

Feel free to visit @ https://cowork-chat.vadosware.io

As soon as I can get myself changed over to an Admin user I'll make it public

**Comment by t3hmrman** [comment]
It looks like this is fixed with the newer version! it's been up a few days and messages are sending fine.
