### ISSUE TITLE
http only not working in docker

### ISSUE THREAD

**Issue by maltokyo** [zulip/docker-zulip#229]
I want to run docker behind an Nginx reverse proxy, which does all of the https for me.  So I want to do this:
https://zulip.readthedocs.io/en/latest/production/deployment.html#configuring-zulip-to-allow-http

I cannot find however how to handle this in the docker version.

**Comment by maltokyo** [comment]
trying the 

`DISABLE_HTTPS: 'True' `

from here: https://github.com/zulip/docker-zulip/issues/137

Will report back if all works ok!

**Comment by rajudev** [comment]
@maltokyo  Did it work ?

**Comment by maltokyo** [comment]
Indeed it works! Will close.

**Comment by timabbott** [comment]
Would it make sense to extend https://zulip.readthedocs.io/en/latest/production/deployment.html#configuring-zulip-to-allow-http to have a link back to https://github.com/zulip/docker-zulip#networking-and-reverse-proxy-configuration so it's easier for folks to find the information?
