### ISSUE TITLE
Thumbnails not generating for images

### ISSUE THREAD

**Issue by maltokyo** [zulip/docker-zulip#236]
I have added `THUMBNAIL_IMAGES: 'True'` in the docker-compose file, but thumbnail images do not generate, and in Zulip they look like this:

![image](https://user-images.githubusercontent.com/1388507/72678417-f608ad00-3aa5-11ea-84f8-6645c62bafd6.png)

When I right-click on that missing image icon, I get a URL like this:
https://zulip.example.com/thumbnail?url=user_uploads%2F2%2F12%2F6Q2syhIB_wOKq75WwDXd5Ct8%2FIMG_6759.PNG&size=thumbnail

And it shows a page with: "You are not authorized to view this file."

What is needed to get thumbnails working?

**Comment by timabbott** [comment]
The THUMBNAIL_IMAGES setting isn't something you can use in production right now.  Unfortunately, due to thumbor having stopped being maintained upstream, we never completed the integration.  It's still technically possible to configure the (alpha) thumbor integration, but it's probably not worth explaining how to do that since we're planning to delete it once we figure out an alternative tool to use instead.  (Effectively, the problem you have there is you've told Zulip to expect a thumbnailing server is running, without also telling one to be run).

**Comment by maltokyo** [comment]
Hi @timabbott 

I would like to reopen this one, as in 2.1.7 I got thumbnails generating very well with this in the docker-compose.yml file.

```
      SETTING_THUMBNAIL_IMAGES: 'True'
      SETTING_THUMBOR_URL: 'http://127.0.0.1:9995'
```

Now after the upgrade to 3.1 Thumbnails again are broken, and the same error as in the original post here.

I have searched the docs, [here](https://zulip.readthedocs.io/en/latest/subsystems/thumbnailing.html) and [here](https://zulipchat.com/help/share-and-upload-files) and it seems it should be working.  In version 3.1 is there some change to make to the above?  Thank you

**Comment by maltokyo** [comment]
Ah, it works now.  Just for others searching for this topic for Zulip 3, you do NOT anymore need the line: `SETTING_THUMBOR_URL: 'http://127.0.0.1:9995'` and leave only this line: `SETTING_THUMBNAIL_IMAGES: 'True'` it is enough by itself

@timabbott please leave it closed ;)  Apologies as always.

**Comment by maltokyo** [comment]
But, on the android app there are no thumbnails at all.  I only see them on the web version.  @timabbott where should I raise this?  I can open a new issue if needed.  Please advise.
I dont have iOS, so not sure about that

**Comment by timabbott** [comment]
Thumbnailing is in general an experimental feature in Zulip; yours is the only production environment I'm aware of using it as the feature is incomplete.  But #mobile in chat.zulip.org is probably the best place to discuss and try to debug.

**Comment by maltokyo** [comment]
Hi @timabbott I have opened a chat there, and also opened a new issue.  https://github.com/zulip/zulip-mobile/issues/4215

In the docs this is not marked as experimental (is it?)

In 3.1 for me, it seems thumbor is not even getting installed in the docker image.

**Comment by maltokyo** [comment]
@timabbott this is the page I refer to, is it out of date?
https://github.com/zulip/zulip/blob/3ee69f3da9956aa45580696b8ad7fe20b41c1a43/docs/subsystems/thumbnailing.md

**Comment by timabbott** [comment]
That page is a design document for this feature, which has been largely implemented for years but is stuck due to problems with Thumbor upstream.  As discussed in chat.zulip.org I've added a comment about its status.  Sorry for the confusion!
