### ISSUE TITLE
Push notifications sevice stops when restarting docker

### ISSUE THREAD

**Issue by maltokyo** [zulip/docker-zulip#243]
Seems the push notification keys are deleted when the docker is taken down and brought up again (?).  That is the only thing I did in the meantime, no other changes.  Before that push notifications were working fine.

I tried to re-register as below (even with the `--rotate-key`), but got the error `Error: Zulip server auth failure: key does not match role <REMOVED>`

So, push notifications do not work at all now, and I am not sure how to "reset" it all to start from scratch.

`zulip@03ab9eae2afe:/$ /home/zulip/deployments/current/manage.py register_server`
```
The following data will be submitted to the push notification service:
  contact_email: maltokyo@mydomain.com
  hostname: z.mydomain.com
  zulip_org_id: <REMOVED>
  zulip_org_key: <REMOVED>

To register, you must agree to the Zulipchat Terms of Service: https://zulipchat.com/terms/
Do you agree to the Terms of Service? [Y/n] Y

Error: Zulip server auth failure: key does not match role <REMOVED>
```

`zulip@03ab9eae2afe:/$ /home/zulip/deployments/current/manage.py register_server --rotate-key`
```
The following data will be submitted to the push notification service:
  contact_email: maltokyo@mydomain.com
  hostname: z.mydomain.com
  new_org_key: <REMOVED>
  zulip_org_id: <REMOVED>
  zulip_org_key: <REMOVED>

Error: Zulip server auth failure: key does not match role <REMOVED>
```

**Comment by maltokyo** [comment]
Temporary fix to reset everything from scratch, in case this happens to someone else.  (I still am not sure if this will last persistently across container restarts).

Remove these two lines from `zulip-secrets.conf`
```
zulip_org_key = KEYHERE
zulip_org_id = IDHERE
```

Run these commands one after the other as zulip user:
```
/home/zulip/deployments/current/scripts/setup/generate_secrets.py --production
/home/zulip/deployments/current/manage.py register_server
/home/zulip/deployments/current/scripts/restart-server
```

**Comment by stratosgear** [comment]
Just to add on what @maltokyo suggested:

If you connect to your running zulip docker image with a `docker exec -it your_running_zulip bash` do not forget to run a `su zulip` before you execute any of the above three commands, otherwise your `zulip-secrets.sonf` after the first command will be owned by root.

**Comment by timabbott** [comment]
> Seems the push notification keys are deleted when the docker is taken down and brought up again (?). That is the only thing I did in the meantime, no other changes. Before that push notifications were working fine.

I'm puzzled as to how this might happen; the keys are stored in `zulip-secrets.conf`, which should be persistent storage.

**Comment by stratosgear** [comment]
Sorry no direct answer to your question, and with all due respect, since I appreciate all the help given here, but the latest published versions gives me weird issues.

I validate that I also had the same issue here and recreating the secrets solved it for me too.  Still have other errors emailed to me, but at least this specific one has ceased to exist with this fix.

**Comment by maltokyo** [comment]
I don't know why but I just restarted the container now and push still works fine. Not sure what happened...

**Comment by maltokyo** [comment]
This is not happening to me anymore on latest release.  Is everyone ok if I close it?  @stratosgear how about you?

**Comment by stratosgear** [comment]
It does not happen to me (regularly) either.  It **did** happen once, and I had to use the fix you mentioned, but I do not know how I **triggered** it.

Let's close for now, and I'll comment again if it reappears.

**Comment by maltokyo** [comment]
Ok. Closing. Tx
