### ISSUE TITLE
zulip-docker email setting issue

### ISSUE THREAD

**Issue by recolic** [zulip/docker-zulip#248]
I cloned `https://github.com/zulip/docker-zulip.git` and finished the `docker-compose` + `nginx` setup.

Now, I'm trying to access my initial admin account. But where could I find the username & password?

I tried to sign up with `$SETTING_ZULIP_ADMINISTRATOR`, but it's not working.

**Comment by recolic** [comment]
I also tried to run . However, there's something abnormal.

This is my docker-compose.yml:

```
      SETTING_ZULIP_ADMINISTRATOR: 'root@recolic.net'
      SETTING_EMAIL_HOST: 'smtp.recolic.net'  # e.g. smtp.example.com
      SETTING_EMAIL_HOST_USER: 'no-reply@recolic.net'
      SETTING_EMAIL_PORT: '587'
```

I run `su zulip -c '/home/zulip/deployments/current/manage.py send_test_email root@recolic.net'`. Expecting the email from `no-reply@recolic.net` to `root@recolic.net`. However, I got an email from `root@recolic.net` to `root@recolic.net`, and another email from `noreply-w7kkfbus5zaaaaaahjjuswqc@chat.recolic.org` to `root@recolic.net`.

Maybe something goes wrong about the email setting...

**Comment by timabbott** [comment]
`send_test_email` sends emails from the 2 types of sender email addresses that Zulip uses, so that's as expected.  We should perhaps make that more clear in the documentation.

**Comment by timabbott** [comment]
> Now, I'm trying to access my initial admin account. But where could I find the username & password?

This is done via `manage.py generate_realm_creation_link`, which IIRC is run automatically at the end of the installer (and so the output should be at the end of the console log for `docker-zulip` after startup).  And then you create the initial account on the web.
