### ISSUE TITLE
Internal server error 500 after fresh installation using podman-compose

### ISSUE THREAD

**Issue by eksotik** [zulip/docker-zulip#255]
So I'm trying to run zulip on RHEL7 with Podman / Podman-Compose. I'm using docker-compose.yml with some modifications.

version: '2.1'
services:
  database:
    image: 'zulip/zulip-postgresql:10'
    environment:
      POSTGRES_DB: 'zulip'
      POSTGRES_USER: 'zulip'
      # Note that you need to do a manual `ALTER ROLE` query if you
      # change this on a system after booting the postgres container
      # the first time on a host.  Instructions are available in README.md.
      POSTGRES_PASSWORD: 'password2'
    volumes:
      - '/volumes/zulip/postgresql/data:/var/lib/postgresql/data:z'
  memcached:
    image: 'memcached:alpine'
    command:
      - 'sh'
      - '-euc'
      - |
        echo 'mech_list: plain' > "/home/memcache/memcached.conf"
        echo "zulip@docker-zulip_memcached_1:password1" > "/home/memcache/memcached-sasl-db"
        exec memcached -S
    environment:
      SASL_CONF_PATH: '/home/memcache/memcached.conf'
      MEMCACHED_SASL_PWDB: '/home/memcache/memcached-sasl-db'
      MEMCACHED_PASSWORD: 'password1'
    restart: always
  rabbitmq:
    image: 'rabbitmq:3.7.7'
    hostname: zulip-rabbit
    restart: always
    environment:
        RABBITMQ_DEFAULT_USER: 'zulip'
        RABBITMQ_DEFAULT_PASS: 'password3'
    volumes:
      - '/volumes/zulip/rabbitmq:/var/lib/rabbitmq:z'
  redis:
    image: 'redis:alpine'
    command:
      - 'sh'
      - '-euc'
      - |
        echo "requirepass 'password4'" > /etc/redis.conf
        exec redis-server /etc/redis.conf
    environment:
      REDIS_PASSWORD: 'password4'
    volumes:
      - '/volumes/zulip/redis:/data:z'
  zulip:
    image: 'zulip/docker-zulip:2.1.4-0'
    build:
      context: .
      args:
        # Change these if you want to build zulip from a different repo/branch
        ZULIP_GIT_URL: https://github.com/zulip/zulip.git
        ZULIP_GIT_REF: 2.1.4
        # Set this up if you plan to use your own CA certificate bundle for building
        # CUSTOM_CA_CERTIFICATES:
    ports:
      - '80:80'
      - '443:443'
    environment:
      DB_HOST: 'database'
      DB_HOST_PORT: '5432'
      DB_USER: 'zulip'
      SSL_CERTIFICATE_GENERATION: 'self-signed'
      SETTING_MEMCACHED_LOCATION: 'memcached:11211'
      SETTING_RABBITMQ_HOST: 'rabbitmq'
      SETTING_REDIS_HOST: 'redis'
      SECRETS_email_password: '123456789'
      # These should match RABBITMQ_DEFAULT_PASS, POSTGRES_PASSWORD,
      # MEMCACHED_PASSWORD, and REDIS_PASSWORD above.
      SECRETS_rabbitmq_password: 'password3'
      SECRETS_postgres_password: 'password2'
      SECRETS_memcached_password: 'password1'
      SECRETS_redis_password: 'password4'
      SECRETS_secret_key: 'aa6icbp257V33TuGB8ueTTxK'
      SETTING_EXTERNAL_HOST: 'zulip.domain.domain'
      SETTING_ZULIP_ADMINISTRATOR: 'admin@example.com'
      SETTING_EMAIL_HOST: ''  # e.g. smtp.example.com
      SETTING_EMAIL_HOST_USER: 'noreply@example.com'
      SETTING_EMAIL_PORT: '587'
      SETTING_EMAIL_BACKEND: 'django.core.mail.backends.filebased.EmailBackend'
      SETTING_EMAIL_FILE_PATH: '/var/log/zulip/emails'
      # It seems that the email server needs to use ssl or tls and can't be used without it
      SETTING_EMAIL_USE_SSL: 'False'
      SETTING_EMAIL_USE_TLS: 'True'
      ZULIP_AUTH_BACKENDS: 'EmailAuthBackend'
      # Uncomment this when configuring the mobile push notifications service
      # SETTING_PUSH_NOTIFICATION_BOUNCER_URL: 'https://push.zulipchat.com'
    volumes:
      - '/volumes/zulip/zulip:/data:z'
    ulimits:
      nofile:
        soft: 40000
        hard: 50000

I see that every container has started and are running fine. Browsing to the magic link gives Internal Server Error.  install.log seems fine, error.log gives below output:

`Traceback (most recent call last):
  File "/srv/zulip-venv-cache/6176a52fab8737c09656fc8ad0352547e9801c07/zulip-py3-venv/lib/pyth                     on3.6/site-packages/django_pylibmc/memcached.py", line 140, in set
    **COMPRESS_KWARGS)
pylibmc.ServerDown: error 47 from memcached_set: (0x55c62784fbb0) SERVER HAS FAILED AND IS DIS                     ABLED UNTIL TIMED RETRY,  host: memcached:11211 -> libmemcached/connect.cc:720
2020-05-12 06:48:19.774 ERR  [django.pylibmc] MemcachedError: error 47 from memcached_set: (0x                     55c627409e00) SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY,  host: memcached:11211 -> l                     ibmemcached/connect.cc:720
Traceback (most recent call last):
  File "/srv/zulip-venv-cache/6176a52fab8737c09656fc8ad0352547e9801c07/zulip-py3-venv/lib/pyth                     on3.6/site-packages/django/contrib/sessions/backends/base.py", line 202, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/zulip-venv-cache/6176a52fab8737c09656fc8ad0352547e9801c07/zulip-py3-venv/lib/pyth                     on3.6/site-packages/django_pylibmc/memcached.py", line 130, in get
    return super(PyLibMCCache, self).get(key, default, version)
  File "/srv/zulip-venv-cache/6176a52fab8737c09656fc8ad0352547e9801c07/zulip-py3-venv/lib/pyth                     on3.6/site-packages/django/core/cache/backends/memcached.py", line 79, in get
    val = self._cache.get(key)
pylibmc.Error: error 41 from memcached_get(:1:django.contrib.sessions.cache): (0x55c627409e00)                      AUTHENTICATION FAILURE,  host: memcached:11211 -> libmemcached/sasl.cc:292

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/zulip-venv-cache/6176a52fab8737c09656fc8ad0352547e9801c07/zulip-py3-venv/lib/pyth                     on3.6/site-packages/django_pylibmc/memcached.py", line 140, in set
    **COMPRESS_KWARGS)
pylibmc.ServerDown: error 47 from memcached_set: (0x55c627409e00) SERVER HAS FAILED AND IS DIS                     ABLED UNTIL TIMED RETRY,  host: memcached:11211 -> libmemcached/connect.cc:720`

Any ideas how to debug more?

**Comment by timabbott** [comment]
That error is pretty clearly Zulip being unable to reach memcached, which could be authentication not working or being setup wrong (E.g. the passwords not matching).

**Comment by timabbott** [comment]
I believe we've fixed the likely root issue here, which is that the hostname was encoded in the memcached username, in Zulip 2.1.7.  Note that `docker-compose.yml` has some updates required to take advantage of the fix for `docker-zulip`.
