### ISSUE TITLE
REALM_HOSTS should be type array in entrypoint.sh

### ISSUE THREAD

**Issue by krejcar25** [zulip/docker-zulip#258]
As it says in the title. The config option `REALM_HOSTS` is not recognised by `entrypoint.sh` as an array and is instead treated as a str, which causes `manage.py checkconfig` to fail.

Adding `[ "$setting_key" = "REALM_HOSTS" ] || \` to the appropriate if statement in `zulipConfiguration` function seems to resolve this issue.

**Comment by timabbott** [comment]
Indeed.  Want to submit a quick PR?
