### ISSUE TITLE
Error running a subcommand of ./lib/provision.py: sudo -H -- env http_proxy= https_proxy= no_proxy= scripts/lib/install-node Actual error output for the subcommand is just above this.

### ISSUE THREAD

**Issue by 20140103** [zulip/docker-zulip#259]
Error running a subcommand of ./lib/provision.py: sudo -H -- env http_proxy= https_proxy= no_proxy= scripts/lib/install-node
Actual error output for the subcommand is just above this.

**Comment by timabbott** [comment]
> Actual error output for the subcommand is just above this.

The actual error is above, as stated there :)

Based on the command failing, though, it's almost certainly a networking/proxy error.
