### ISSUE TITLE
can you make your Wiki editable? I solved the Apache2 reverse proxy problem ...

### ISSUE THREAD

**Issue by qnxor** [zulip/docker-zulip#261]
... and wanted to write it out next to the Nginx wiki page.

**Comment by timabbott** [comment]
I think our goal is to delete the wiki and just use documentation in the actual repository (which is easier to keep up to date as `git grep` will find references in it).  

Probably we should do the last push to move the remaining bits of useful content and delete it.

**Comment by timabbott** [comment]
We now have good documentation on reverse proxies, https://zulip.readthedocs.io/en/stable/production/reverse-proxies.html plus links from the Docker image instructions.

We still need to finish deleting the wiki: #170.
