### ISSUE TITLE
3.0-0 is not available on docker hub

### ISSUE THREAD

**Issue by luckyraul** [zulip/docker-zulip#264]
@timabbott 3.0-0 is not available on docker hub

**Comment by andersk** [comment]
The build is still “pending”.

**Comment by luckyraul** [comment]
commit was 16 hours ago

**Comment by timabbott** [comment]
We might need to cancel and restart the build; seems unlikely DockerHub is going to run it.

**Comment by timabbott** [comment]
https://status.docker.com/pages/history/533c6539221ae15e3f000031 confirms we need to do that.

Just tried cancelling and retriggering the "master" build.  Might need to do another for the 3.0 tag.

**Comment by H8to** [comment]
@timabbott The build is available now. I guess the issue can be closed.
I have some trouble after the update though. Will open an issue :)
