### ISSUE TITLE
upload postgres database to s3 bucket having issues 

### ISSUE THREAD

**Issue by amolvishwakarma** [zulip/docker-zulip#273]
I have used this method to upload postgres database to s3 bucket , I am running zulip in docker image ,version of zulip is 2.1.7 .
In my case I didnt find the puppet/zulip/manifests/postgres_backups.pp there is no file with this name , any help will be appreciated 

![image](https://user-images.githubusercontent.com/57523705/93330851-0fcce080-f83d-11ea-95c7-8f136c5c189e.png)

**Comment by timabbott** [comment]
That file is new in Zulip 3.0; I recommend upgrading.  See https://zulip.readthedocs.io/en/latest/production/upgrade-or-modify.html.

**Comment by amolvishwakarma** [comment]
Thanks @timabbott
