### ISSUE TITLE
certbot may fail to install because /var/lib/apt/lists/ is cleaned out

### ISSUE THREAD

**Issue by alexmv** [zulip/docker-zulip#275]
The last step of the Dockerfile is to clean out the apt data.  At runtime, `entrypoint.sh` may try to `apt-get install certbot` via `scripts/setup/setup-certbot`, which fails because there is no prior `apt-get update`.

**Comment by timabbott** [comment]
I think we need to add an `apt-get update` there; in that even if we had apt data, it'd be stale at runtime (which often leads to installation failures anyway, e.g. the version in the image being already gone).
