### ISSUE TITLE
Backing up postgres database to s3 

### ISSUE THREAD

**Issue by amolvishwakarma** [zulip/docker-zulip#276]
Applied puppet config for postgres backup but it is not creating files in /usr/local/bin/pg_backup_and_purge.py and unable to run check postgres backup it says no module found dateutil.

**Comment by amolvishwakarma** [comment]
Currently shifted to version 3.1 docker image as per @timabbott  suggested

**Comment by timabbott** [comment]
@amolvishwakarma can you confirm that upgrading to 3.x resolved the issue you were seeing?  I'm closing this as the symptom reported here is definitely from using an old version that didn't have the new backup features in 3.x.

**Comment by amolvishwakarma** [comment]
There is still issue @timabbott , I had applied the puppet config for postgres backup pp file but it is not creating file at /usr/* postgres backup and purge py file , I found the file under nagios plugins and while executing the file it says no module found dateutil
