### ISSUE TITLE
Issue has been closed and didnt find out any solution 

### ISSUE THREAD

**Issue by amolvishwakarma** [zulip/docker-zulip#278]
![image](https://user-images.githubusercontent.com/57523705/94772127-9275a400-03d6-11eb-9038-3afaa2b8e1a9.png)
Adding screenshot of issue and last conversation please suggest the steps to perform to resolve the issue .

**Comment by timabbott** [comment]
What documentation are you looking at?  We support `manage.py backup` with `docker-zulip` as documented, but it looks like you're looking for the `wal-e` based system?

You need to include the `postgres_backups.pp` Puppet rule; I'm not sure there's a convenient way to do that in `docker-zulip` without manually configuring `zulip.conf`.

@alexmv FYI.

**Comment by amolvishwakarma** [comment]
Yes sorry for my english, I am using postgres_backups.pp puppet rule while applying the rule it works fine but when I checked  in s3 bucket it is empty ,  it is not dumping db on s3 backup please let me know the way to troubleshoot the issue @timabbott

**Comment by alexmv** [comment]
> You need to include the postgres_backups.pp Puppet rule; I'm not sure there's a convenient way to do that in docker-zulip without manually configuring zulip.conf.

Tangentially fixed in zulip#16590.

Also, to be explicit for metadata purposes, this is a continuation of #276.

**Comment by amolvishwakarma** [comment]
Thanks @alexmv , I will look at zulip/zulip#16590.

**Comment by alexmv** [comment]
It may also be that in docker, cron needs to explicitly be restarted/reloaded to pick up the new cron rule.  I'll experiment briefly.

**Comment by timabbott** [comment]
`cron` runs in supervisord in `docker-zulip`, so that seems plausible.
