### ISSUE TITLE
Zulip server crashed suddenly 

### ISSUE THREAD

**Issue by amolvishwakarma** [zulip/docker-zulip#288]
Hi, I am facing an issue with the docker-zulip server it suddenly crashed running version 2.1.7-0
Ram: 2gb 
I tried to figure out checking logs but didn't figure out the exact issue please suggest the way to fix this

**Comment by timabbott** [comment]
We can't do any meaningful debugging without logging details.  I'm not aware of any issues in Zulip that would cause random crashes, though the first thing I'd look for is an OOM kill on the system.

Also, I'd recommend upgrading to 3.x -- there are a lot of improvements, including to the Docker integration.
