### ISSUE TITLE
Not serving css js images files with nginx proxy setup

### ISSUE THREAD

**Issue by flashery** [zulip/docker-zulip#296]
I tried installing this docker image on my ec2 instance machine with NGINX web server. But the static file is not displaying on my site when using HTTPS.. https://zp.tastysites.dev

What seems to be lacking here? can you help?

here is the nginx config

```
server {


	server_name zp.tastysites.dev;

	location / {
		proxy_pass	https://127.0.0.1:5553;
	}



    listen 443 ssl; # managed by Certbot
    certbots ssl here .....

}
```

**Comment by flashery** [comment]
Update:
Here is what I found. The webpack bundle files is being rendered using https://localhost.localdomain while other files is rendered the correct url  https://zp.tastysites.dev

![image](https://user-images.githubusercontent.com/236919/117585116-3b416a00-b143-11eb-826f-56af0cd84ee1.png)

**Comment by eriktews** [comment]
You are supposed to modify `SETTING_EXTERNAL_HOST` in `docker-compose.yml`. When you set it to `zp.tastysites.dev` then it should work fine.

**Comment by niaou73** [comment]
Hello,
I have the same issue. I want to put zulip behind haproxy.
I first disabled https and tryed to access it without haproxy first. When I access to http://localhost, the page is served, but the js and css have a problem. I get them as 0o sized.

Here is my docker-compose config : 
`  zulip:
    image: "zulip/docker-zulip:${ZULIP_TAG}"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      DB_HOST: "zulip-db"
      DB_HOST_PORT: "5432"
      DB_USER: ${ZULIP_DB_USER}
      SSL_CERTIFICATE_GENERATION: "self-signed"
      SETTING_MEMCACHED_LOCATION: "memcached:11211"
      SETTING_RABBITMQ_HOST: "rabbitmq"
      SETTING_REDIS_HOST: "redis"
      SECRETS_email_password: ${SMTP_PASSWORD}
      # These should match RABBITMQ_DEFAULT_PASS, POSTGRES_PASSWORD,
      # MEMCACHED_PASSWORD, and REDIS_PASSWORD above.
      SECRETS_rabbitmq_password: ${RABBITMQ_PASSWORD}
      SECRETS_postgres_password: ${ZULIP_DB_PASSWORD}
      SECRETS_memcached_password: ${MEMCACHED_PASSWORD}
      SECRETS_redis_password: ${REDIS_PASSWORD}
      SECRETS_secret_key: ${ZULIP_SECRET}
      SETTING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
      SETTING_EXTERNAL_HOST: "localhost"
      SETTING_EXTERNAL_URI_SCHEME: "http://localhost"
      SETTING_ZULIP_ADMINISTRATOR: ${ZULIP_ADMIN}
      SETTING_EMAIL_HOST: ${SMTP_HOST} # e.g. smtp.example.com
      SETTING_EMAIL_HOST_USER: ${SMTP_USER}
      SETTING_EMAIL_PORT: ${SMTP_PORT}
      # It seems that the email server needs to use ssl or tls and can't be used without it
      SETTING_EMAIL_USE_SSL: ${SMTP_SSL}
      SETTING_EMAIL_USE_TLS: ${SMTP_TLS}
      ZULIP_AUTH_BACKENDS: "EmailAuthBackend"
      # Uncomment this when configuring the mobile push notifications service
      # SETTING_PUSH_NOTIFICATION_BOUNCER_URL: 'https://push.zulipchat.com'
      DISABLE_HTTPS: "True"
    volumes:
      - "${STORAGE_PATH}/zulip:/data:rw"
    ulimits:
      nofile:
        soft: 1000000
        hard: 1048576`

ZULIP_TAG is equal to 5.2-0
![Uploading Capture d’écran du 2022-05-05 09-34-06.png…]()

**Comment by Suchyy** [comment]
Hi,
I have the same issue. I want to test Zulip locally before deployment with SSL and domain. I tried SETTING_EXTERNAL_HOST with host IP and host IP with PORT. I have DISABLE_HTTPS: "True" too. I am accessing site with HTTP but calls for resources are in HTTPS and they are blocked.
How to make it work?

**Comment by timabbott** [comment]
We now have good documentation on reverse proxies, https://zulip.readthedocs.io/en/stable/production/reverse-proxies.html plus links from the Docker image instructions.
