### ISSUE TITLE
Giphy 404

### ISSUE THREAD

**Issue by jwillmer** [zulip/docker-zulip#298]
I added a API key for Giphy and I can select GIFs from the input menu but they are not displayed. 

![image](https://user-images.githubusercontent.com/1503577/119129660-7e4ee780-ba37-11eb-8f91-b280c4513eea.png)

![image](https://user-images.githubusercontent.com/1503577/119129816-b48c6700-ba37-11eb-9f61-19f39ebb6da8.png)

I think the `show preview images` does not work on my deployment. My instance is behind a reverse proxy (traefik) that proxies the SSL connection. The Zulip instance is running via HTTP (port 80). I don't know if that might be a problem.

**Comment by timabbott** [comment]
Based on that URL, I think this issue is that we don't have `camo` enabled in `docker-zulip`.  Details are here:

https://chat.zulip.org/#narrow/stream/3-backend/topic/camo.20in.20docker-zulip/near/1182922

**Comment by jwillmer** [comment]
[Same issue from 2019!](https://github.com/zulip/docker-zulip/issues/179)

**Comment by jwillmer** [comment]
This environment setting fixed it for me: `ZULIP_CUSTOM_SETTINGS: CAMO_URI = ""`

It is just a workaround and should be fixed. So I leave this issue open to track progress.

**Comment by eXtrem0us** [comment]
> This environment setting fixed it for me: `ZULIP_CUSTOM_SETTINGS: CAMO_URI = ""`
> 
> It is just a workaround and should be fixed. So I leave this issue open to track progress.

It worked for me. Thank you!
