### ISSUE TITLE
Setting NOREPLY_EMAIL_ADDRESS

### ISSUE THREAD

**Issue by shadow7412** [zulip/docker-zulip#302]
I had hoped that setting SETTING_NOREPLY_EMAIL_ADDRESS on the zulip container would catch this, but it doesn't seem to.

Is there a way to set this from the docker-compose file?
Is there a way to set arbitrary settings, or do they all need to be mapped?

**Comment by amon-ra** [comment]
SETTING_ADD_TOKENS_TO_NOREPLY_ADDRESS: 'False' in environment inside docker-compose.yaml works for me

**Comment by timabbott** [comment]
The solution found here is the intended workflow, and it is documented, so I don't think there's anything to change here other than general improvements in organization for the documentation on specifying settings.
