### ISSUE TITLE
Can't upgrade (from 3.4 to 4.2), get pip installation error

### ISSUE THREAD

**Issue by panomitrius** [zulip/docker-zulip#303]
I'm runing Zulip 3.4 and can't upgrade to the latest version, running into an error with PIP (using docker).
I'm running Ubuntu 20.04.2 with all packages updated.
I tried updating changing the docker-compose.yml file to the latest versions according to https://github.com/zulip/docker-zulip/blob/master/docker-compose.yml - then running:
docker-compose stop
docker-compose up

The output is:

`+ /srv/zulip-venv-cache/25814377d5327003b07463da43a579da4b2d9543/zulip-py3-venv/bin/pip install --no-deps --require-hashes --requirement /root/zulip/requirements/prod.txt`

Error running a subcommand of /root/zulip/scripts/lib/create-production-venv: /srv/zulip-venv-cache/25814377d5327003b07463da43a579da4b2d9543/zulip-py3-venv/bin/pip install --no-deps --require-hashes --requirement /root/zulip/requirements/prod.txt
Actual error output for the subcommand is just above this.

`pip install` failed; retrying...
+ /srv/zulip-venv-cache/25814377d5327003b07463da43a579da4b2d9543/zulip-py3-venv/bin/pip install --force-reinstall --require-hashes --requirement /root/zulip/requirements/pip.txt
+ /srv/zulip-venv-cache/25814377d5327003b07463da43a579da4b2d9543/zulip-py3-venv/bin/pip install --no-deps --require-hashes --requirement /root/zulip/requirements/prod.txt

Error running a subcommand of /root/zulip/scripts/lib/create-production-venv: /srv/zulip-venv-cache/25814377d5327003b07463da43a579da4b2d9543/zulip-py3-venv/bin/pip install --no-deps --require-hashes --requirement /root/zulip/requirements/prod.txt
Actual error output for the subcommand is just above this.

Traceback (most recent call last):
  File "/root/zulip/scripts/lib/setup_venv.py", line 335, in do_setup_virtualenv
    install_venv_deps(pip, requirements_file)
  File "/root/zulip/scripts/lib/setup_venv.py", line 101, in install_venv_deps
    run([pip, "install", "--no-deps", "--require-hashes", "--requirement", requirements_file])
  File "/root/zulip/scripts/lib/zulip_tools.py", line 198, in run
    subprocess.check_call(args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/srv/zulip-venv-cache/25814377d5327003b07463da43a579da4b2d9543/zulip-py3-venv/bin/pip', 'install', '--no-deps', '--require-hashes', '--requirement', '/root/zulip/requirements/prod.txt']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/zulip/scripts/lib/create-production-venv", line 37, in <module>
    os.path.join(ZULIP_PATH, "requirements", "prod.txt"))
  File "/root/zulip/scripts/lib/setup_venv.py", line 294, in setup_virtualenv
    do_setup_virtualenv(cached_venv_path, requirements_file)
  File "/root/zulip/scripts/lib/setup_venv.py", line 339, in do_setup_virtualenv
    install_venv_deps(pip, requirements_file)
  File "/root/zulip/scripts/lib/setup_venv.py", line 101, in install_venv_deps
    run([pip, "install", "--no-deps", "--require-hashes", "--requirement", requirements_file])
  File "/root/zulip/scripts/lib/zulip_tools.py", line 198, in run
    subprocess.check_call(args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/srv/zulip-venv-cache/25814377d5327003b07463da43a579da4b2d9543/zulip-py3-venv/bin/pip', 'install', '--no-deps', '--require-hashes', '--requirement', '/root/zulip/requirements/prod.txt']' returned non-zero exit status 1.

Zulip installation failed (exit code 1)!

The install process is designed to be idempotent, so you can retry after resolving whatever issue caused the failure (there should be a traceback above). A log of this installation is available in /var/log/zulip/install.log
ERROR: Service 'zulip' failed to build : The command '/bin/sh -c dpkg-divert --add --rename /etc/init.d/nginx &&     ln -s /bin/true /etc/init.d/nginx &&     mkdir -p "$DATA_DIR" &&     cd /root &&     tar -xf zulip-server-docker.tar.gz &&     rm -f zulip-server-docker.tar.gz &&     mv zulip-server-docker zulip &&     cp -rf /root/custom_zulip/* /root/zulip &&     rm -rf /root/custom_zulip &&     export PUPPET_CLASSES="zulip::dockervoyager"            DEPLOYMENT_TYPE="dockervoyager"            ADDITIONAL_PACKAGES="expect" &&     /root/zulip/scripts/setup/install --hostname="$(hostname)" --email="docker-zulip" --no-init-db &&     rm -f /etc/zulip/zulip-secrets.conf /etc/zulip/settings.py &&     apt-get -qq autoremove --purge -y &&     apt-get -qq clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 1`

**Comment by timabbott** [comment]
It looks like this is a failure building a container, so you're not using the containers we provide on dockerhub (you may need to change something in your `docker-compose.yml`).  The actual failure is probably something about networking or memory on your system.  You appear to have left off the first error in that traceback, so I can't tell what.
