### ISSUE TITLE
Install docker

### ISSUE THREAD

**Issue by hygolei** [zulip/docker-zulip#316]
Hi

I'm having an error when installing the zulip docker related with yarn install
The problem is a timeout in the instalation of yarn

I'm trying to install in a dokker behind a firewal

best regards,

ERROR

info There appears to be trouble with your network connection. Retrying...
verbose 74.915757211 Error: https://registry.yarnpkg.com/3d-view/-/3d-view-2.0.0.tgz: tunneling socket could not be established, cause=socket hang up
    at ClientRequest.onError (/srv/zulip-yarn/lib/cli.js:152235:17)
    at Object.onceWrapper (events.js:483:26)
    at ClientRequest.emit (events.js:376:20)
    at Socket.socketOnEnd (_http_client.js:499:9)
    at Socket.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
error An unexpected error occurred: "https://registry.yarnpkg.com/3d-view/-/3d-view-2.0.0.tgz: tunneling socket could not be established, cause=socket hang up".
info If you think this is a bug, please open a bug report with the information provided in "/srv/zulip-npm-cache/eddc4d05d4217740fedbe70a1f291ef17a828c80/yarn-error.log".

Error running a subcommand of ./lib/provision.py: /srv/zulip-yarn/bin/yarn install --non-interactive --frozen-lockfile --prefer-offline --network-timeout=1000000 --verbose
Actual error output for the subcommand is just above this.

**Comment by timabbott** [comment]
The problem is that your firewall is blocking outgoing HTTP access to Zulip's dependencies.  That code only runs when building an image, so your actual problem may have been not running `docker-compose pull` how you'd intended to (i.e. you're building the image from source rather than running the prebuilt images).

**Comment by timabbott** [comment]
I don't think there's any relevant change we can make here.
