### ISSUE TITLE
Error when pulling image "manifest for zulip/docker-zulip:4.6-0 not found: manifest unknown"

### ISSUE THREAD

**Issue by maltokyo** [zulip/docker-zulip#323]
When upgrading, docker cant find the new image.  Anyone else?

```
root@myhost:~/docker-zulip# docker pull zulip/docker-zulip:4.6-0
Error response from daemon: manifest for zulip/docker-zulip:4.6-0 not found: manifest unknown: manifest unknown
```

**Comment by maltokyo** [comment]
Oh, 4.6 isn't built yet
https://hub.docker.com/r/zulip/docker-zulip/tags?page=1&ordering=last_updated

@andersk - could you please trigger it?

**Comment by andersk** [comment]
It seems Docker Hub stopped doing free cloud builds (though they were working for longer than they had [announced](https://www.docker.com/blog/changes-to-docker-hub-autobuilds/)). I’ll push a build from my own hardware.

**Comment by maltokyo** [comment]
Thank you
