### ISSUE TITLE
Docker default external domain doesn't work on windows

### ISSUE THREAD

**Issue by abdulzeedo** [zulip/docker-zulip#326]
Hi all,

the default external domain is set to 'local.localdomain'. I think unless we manually set a dns resolver in the user host file, this domain will not work. Resulting in a broken website with no styling nor images. 

We could improve the docker-compose file to warn the users and offer an alternative for windows.

**Comment by timabbott** [comment]
Is there an alternative you've seen used for other Docker images that work on windows without configuration?  I'm not familiar with how networking is setup in Docker on Windows in general.

**Comment by timabbott** [comment]
Closing due to lack of an obvious change to make here.
