### ISSUE TITLE
docker-zulip:4.8-0 missing on Dockerhub 

### ISSUE THREAD

**Issue by ArjonBu** [zulip/docker-zulip#329]
Hello, 

Version 4.8-0 is missing on [Dockerhub](https://hub.docker.com/r/zulip/docker-zulip/tags).

Is there any plan to add it?

Thank you in advance.

**Comment by luckyraul** [comment]
@timabbott again

**Comment by alexmv** [comment]
Pushed!  Apologies for the delay.
