### ISSUE TITLE
Cannot login on local dummy install: "Internal Server Error"

### ISSUE THREAD

**Issue by WorldsEndless** [zulip/docker-zulip#331]
I am trying to follow along with the documentation and things went well for the install. Finally, with a =docker-compose up= I get a server I can visit in the browser, taking me to login. However, upon any attempt to log on, it fails and the cute octopus tells me, "Internal Server Error". I don't know where to find further info on what the error might be. Is it possible this is because of my email settings, which are completely made up since this was just to be a dummy test-run on my machine before we put it on a real server?

**Comment by timabbott** [comment]
@WorldsEndless the same place as in a normal server (https://zulip.readthedocs.io/en/latest/production/troubleshooting.html), just ssh into the container before looking for `/var/log/zulip/errors.log` file.

**Comment by WorldsEndless** [comment]
ok. Mission accomplished. For anyone rusty on Docker, like me, here is the command I used to ssh in:

```
docker exec -it docker-zulip_zulip_1 /bin/bash
```
that done I made my way to `/var/log/zulip/` and ran a `tail errors.log -f` and watched as I attempted to log in with my browser. Here is what I saw:

> 2021-12-11 00:18:41.746 ERR  [django.request] Internal Server Error: /accounts/login/
> Traceback (most recent call last):
>   File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
>     response = get_response(request)
>   File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/home/zulip/deployments/2021-12-08-22-24-29/./zerver/lib/request.py", line 390, in _wrapped_view_func
>     return view_func(request, *args, **kwargs)
>   File "/home/zulip/deployments/2021-12-08-22-24-29/./zerver/views/auth.py", line 750, in login_page
>     template_response = DjangoLoginView.as_view(
>   File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
>     return bound_method(*args, **kwargs)
>   File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
>     return view(request, *args, **kwargs)
>   File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
>     return bound_method(*args, **kwargs)
>   File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
>     response = view_func(request, *args, **kwargs)
>   File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
>     return bound_method(*args, **kwargs)
>   File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
>     response = view_func(request, *args, **kwargs)
>   File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/contrib/auth/views.py", line 63, in dispatch
>     return super().dispatch(request, *args, **kwargs)
>   File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
>     return handler(request, *args, **kwargs)
>   File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/views/generic/edit.py", line 141, in post
>     if form.is_valid():
>   File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/forms/forms.py", line 175, in is_valid
>     return self.is_bound and not self.errors
>   File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/forms/forms.py", line 170, in errors
>     self.full_clean()
>   File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/forms/forms.py", line 373, in full_clean
>     self._clean_form()
>   File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/forms/forms.py", line 400, in _clean_form
>     cleaned_data = self.clean()
>   File "/home/zulip/deployments/2021-12-08-22-24-29/./zerver/forms.py", line 388, in clean
>     realm = get_realm(subdomain)
>   File "/home/zulip/deployments/2021-12-08-22-24-29/./zerver/models.py", line 763, in get_realm
>     return Realm.objects.get(string_id=string_id)
>   File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
>     raise self.model.DoesNotExist(
> zerver.models.Realm.DoesNotExist: Realm matching query does not exist.

Does any of that mean anything to anyone in the know?

**Comment by WorldsEndless** [comment]
looks like there might be a related thing in the non-docker queue. Did I miss a step in the setup? https://github.com/zulip/zulip/issues/19652

**Comment by WorldsEndless** [comment]
Solved! This line from the documentation did the trick.  This should be mentioned as a required step. In fact, it would be nice if this was part of the setup.  https://github.com/zulip/docker-zulip#running-management-commands

```
docker-compose exec -u zulip zulip \
    /home/zulip/deployments/current/manage.py generate_realm_creation_link
```

**Comment by timabbott** [comment]
Reopening, since we should tweak the documentation following this.

**Comment by ja49619** [comment]
UP, you should use quotes for the command otherwise it won't work
`... " /home/zulip/deployments/current/manage.py generate_realm_creation_link"`

**Comment by timabbott** [comment]
Thanks @ja49619, just pushed a documentation update fixing this, including your quoting suggestion. Feedback/follow-up PRs appreciated!
