### ISSUE TITLE
All users are offline after update from 3.4 zulip container to newest one

### ISSUE THREAD

**Issue by Eljaja** [zulip/docker-zulip#332]
![image](https://user-images.githubusercontent.com/15385141/145681359-2652b275-53b1-44c4-924d-6f650aa06a6f.png)

there is nothing interesting in the logs

**Comment by timabbott** [comment]
This sort of issue best debugged interactively in chat.zulip.org, but my guess is your presence queue worker (or possibly all queue workers) is not running, and thus presence updates sent from clients aren't being processed.  `supervisorctl status` inside the container might be instructive.

**Comment by sjmgarnier** [comment]
Same issue here after upgrading to 4.8.

**Comment by sjmgarnier** [comment]
FYI, `supervisorctl status` returns that all processes are running.

**Comment by timabbott** [comment]
I'd be very surprised if whatever the issue was here is still present in 9.0. If anyone else sees a similar symptom, I'd check the logs as documented in Zulip's troubleshooting guide.
