### ISSUE TITLE
Kubernetes persistance seems not working after a restart

### ISSUE THREAD

**Issue by yevon** [zulip/docker-zulip#338]
I'm having issues having zulip working in kubernetes. I've managed to have it working, creating a realm etc, but when I restart, is like everything gets erased, and it shows again an error when trying to login as if the realm was never created.

I've seen some issues with given kubernetes example config. For example the Redis mount path doesn't match with the one in the docker-compose.yaml. In kubernetes states the mount path as /var/lib/redis, and in docker-compose as /data.

Also when I uncomment the line PUSH_NOTIFICATION_BOUNCER_URL in the kubernetes config file, it doesn't make any effect inside the zulip py config file, and appears commented again. 

![image](https://user-images.githubusercontent.com/121157/148624301-0f8f33af-c4c0-46f2-b694-699f3febf7fd.png)

Maybe I'm missing some steps. Apart from creating the realm, should I do anything else on first start?

I created persistent volumes, and the config file I used is:

apiVersion: v1
kind: ReplicationController
metadata:
  name: zulip
  labels:
    version: 1.8.1-0
    app: zulip
spec:
  replicas: 1
  selector:
    version: 1.8.1-0
    app: zulip
  template:
    metadata:
      labels:
        version: 1.8.1-0
        app: zulip
    spec:
      containers:
        - name: redis
          image: quay.io/sameersbn/redis:latest
          env:
            - name: REDIS_PASSWORD
              value: XXXXXXX
          volumeMounts:
            - name: zulip-redis-persistent-storage
              mountPath: /data
        - name: memcached
          image: quay.io/sameersbn/memcached:latest
        - name: rabbitmq
          image: rabbitmq:3.7.7
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "zulip"
            - name: RABBITMQ_DEFAULT_PASS
              value: "XXXXXX"
          volumeMounts:
            - name: zulip-rabbitmq-persistent-storage
              mountPath: /var/lib/rabbitmq
        - name: postgresql
          image: zulip/zulip-postgresql
          env:
            - name: POSTGRES_DB
              value: zulip
            - name: POSTGRES_USER
              value: zulip
            - name: POSTGRES_PASSWORD
              value: XXXXXXX
          volumeMounts:
            - name: zulip-postgresql-persistent-storage
              mountPath: /var/lib/postgresql
        - name: zulip
          image: zulip/docker-zulip:4.8-1
          env:
            - name: DB_HOST
              value: "localhost"
            - name: MEMCACHED_HOST
              value: "localhost"
            - name: REDIS_HOST
              value: "localhost"
            - name: RABBITMQ_HOST
              value: "localhost"
            - name: ZULIP_AUTH_BACKENDS
              value: "EmailAuthBackend"
            - name: SECRETS_email
              value: "XXXXX"
            - name: SETTING_EXTERNAL_HOST
              value: "XXXXX.com"
            - name: SETTING_ZULIP_ADMINISTRATOR
              value: "XXXXX@gmail.com"
            - name: SETTING_EMAIL_HOST
              value: "smtp.gmail.com"
            - name: SETTING_EMAIL_HOST_USER
              value: "XXXXX@gmail.com"
            - name: SECRETS_email_password
              value: "XXXXXX"
            - name: SETTING_EMAIL_PORT
              value: "587"
            - name: SETTING_EMAIL_USE_SSL
              value: "False"
            - name: SETTING_EMAIL_USE_TLS
              value: "True"
            - name: ZULIP_USER_EMAIL
              value: "XXXXXX@gmail.com"
            - name: ZULIP_USER_DOMAIN
              value: "XXXXXX.com"
            - name: ZULIP_USER_PASS
              value: "XXXXXX"
            - name: SECRETS_secret_key
              value: "REPLCAE_WITH_SECURE_SECRET_KEY"
            - name: SECRETS_postgres_password
              value: "XXXXXX"
            - name: SECRETS_rabbitmq_password
              value: "XXX"
            - name: SECRETS_redis_password
              value: XXXXXXX
            - name: SSL_CERTIFICATE_GENERATION
              value: "self-signed"
            - name: DISABLE_HTTPS
              value: "True"
            - name: PUSH_NOTIFICATION_BOUNCER_URL
              value: 'https://push.zulipchat.com'
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
          volumeMounts:
            - name: zulip-persistent-storage
              mountPath: /data
      volumes:
        - name: zulip-redis-persistent-storage
          persistentVolumeClaim:
            claimName: pvc-zulip-redis
        - name: zulip-rabbitmq-persistent-storage
          persistentVolumeClaim:
            claimName: pvc-zulip-rabbitmq
        - name: zulip-postgresql-persistent-storage
          persistentVolumeClaim:
            claimName: pvc-zulip-postgres
        - name: zulip-persistent-storage
          persistentVolumeClaim:
            claimName: pvc-zulip-zulip

**Comment by yevon** [comment]
PUSH_NOTIFICATION_BOUNCER_URL parameter is not correct, it must be SETTING_PUSH_NOTIFICATION_BOUNCER_URL

**Comment by yevon** [comment]
Every time postgres is restarted, the database gets recreated. There is something wrong with the start command.

**Comment by timabbott** [comment]
I can't tell what the misconfiguration is, but this is likely some sort of misconfiguration with how persistent the persistent storage given to the postgres host was.
