### ISSUE TITLE
kubernestes server error

### ISSUE THREAD

**Issue by oksanassss** [zulip/docker-zulip#342]
hi. when I deployed to kubernetes  , I'm getting this error :
```
Internal server error
This Zulip server is currently experiencing some technical difficulties. Sorry about that!
The page will reload automatically soon after service is restored.
```
Has anyone seen this error before?

**Comment by akisys** [comment]
hi @oksanassss 

I've just debugged the same message and narrowed it down by checking the `/var/log/zulip/error.log` spreading error messages about the trusted proxy configuration being incomplete.

I've added the following Zulip environment variable to my helm values file:
```
zulip:
  environment:
    LOADBALANCER_IPS: "127.0.0.1, 10.0.0.0/8"
```

The localhost address is usually already in the container config, but the 10.0.0.0/8 range is not, and that is where typically the cluster uses subnets for the Ingress Controller pods.
You may also narrow it further down to the pod IP of the Ingress Controller, but this seemed counter productive for the helm-chart install I'm debugging.

Hope this helps!
