### ISSUE TITLE
ZulipLDAPAuthBackend with Docker compose requires manual configuration

### ISSUE THREAD

**Issue by blizzard4591** [zulip/docker-zulip#344]
Dear all,
we are trying to set up Zulip via Docker, but want to connect it to our existing LDAP.
Is there a supported way of passing the required data to the generated config file?
The parsing of ENV variables seems to not include `auth_ldap_bind_password`, `AUTH_LDAP_USER_SEARCH `, etc...

Thank you for your help

**Comment by misaflo** [comment]
Hello,
This is my LDAP configuration:
    
    ZULIP_AUTH_BACKENDS: "EmailAuthBackend,ZulipLDAPAuthBackend"
    SETTING_AUTH_LDAP_SERVER_URI: "ldaps://..."
    SETTING_AUTH_LDAP_BIND_DN: ""
    SECRETS_auth_ldap_bind_password: ""
    SETTING_AUTH_LDAP_USER_SEARCH: 'LDAPSearch("dc=...,dc=fr",
        ldap.SCOPE_SUBTREE, "(uid=%(user)s)")'
    SETTING_AUTH_LDAP_REVERSE_EMAIL_SEARCH: 'LDAPSearch("dc=...,dc=fr",
        ldap.SCOPE_SUBTREE, "(mail=%(email)s)")'
    SETTING_LDAP_APPEND_DOMAIN: None
    SETTING_AUTH_LDAP_USERNAME_ATTR: "uid"
    SETTING_LDAP_EMAIL_ATTR: "mail"
    SETTING_AUTH_LDAP_USER_ATTR_MAP: '{ "first_name": "givenName", "last_name": "sn" }'

**Comment by timabbott** [comment]
You can do this using MANUAL_CONFIGURATION. The problem is that the `LDAPSearch` type of Python class that we need to pass through to the LDAP system can't be readily passed through environment variables :(.
