### ISSUE TITLE
How to setup Docker Zulip emails for local delivery?

### ISSUE THREAD

**Issue by WorldsEndless** [zulip/docker-zulip#348]
We would like to set up our Docker Zulip installation to receive emails-to-thread and email replies, as per https://zulip.readthedocs.io/en/latest/production/email-gateway.html . Is there any way of configuring local delivery through the Docker instance?

This may be related to #222

**Comment by wynandt-sa** [comment]
Hi

Were you able to figure this out?

Thanks

**Comment by timabbott** [comment]
I think this is currently not easy to do without a lot of effort. https://github.com/zulip/docker-zulip/issues/237 is the most detailed issue on it, closing to reduce duplicates.
