### ISSUE TITLE
5.2

### ISSUE THREAD

**Issue by maltokyo** [zulip/docker-zulip#354]
Is there a plan to move up to 5.2?  Cant see it yet in tags, and wondering if there might be some issue.

**Comment by alexmv** [comment]
We pushed the [5.2 image to docker hub](https://hub.docker.com/layers/207896152/zulip/docker-zulip/5.2-0/images/sha256-c8d33f2359286ae80e244e5721bfd8d4cd337e159a904be4435a4666898f5978?context=repo), but apparently I forgot to push that tag to this repo.  I've just done so -- sorry for the confusion!
