### ISSUE TITLE
No desktop notifications on Windows

### ISSUE THREAD

**Issue by thothi** [zulip/docker-zulip#358]
We've had a Zulip server running on version 4.6 for a while, but my users told me they are not receiving any desktop notifications on Windows (those popup notifications bottom right Windows generates). After some testing it seemed like this is not a client issue.

I therefore upgraded the Zulip server to 5.2, however the same issue persisted. 
Then I went ahead and created a fresh test VM and did a fresh install of 5.2. Sadly the same issue still persisted. 
My next step was to install Zulip without docker using the [official guide](https://zulip.readthedocs.io/en/stable/production/install.html) and suddenly desktop notifications started to work.

I still have the docker-zulip server where notifications don't work if you want me to debug anything. Happy to look into this, but I don't see any errors related to this.

**Comment by timabbott** [comment]
This is very likely unrelated to Docker. I don't think it's possible for how the server is hosted to matter. So there must have been some other missing variable here (maybe an unusual/invalid hostname that made the browser not want to prompt about notifications).
