### ISSUE TITLE
500 internal server error in k8s pod when curl localhost

### ISSUE THREAD

**Issue by Kyriedk** [zulip/docker-zulip#361]
hi,guys, i got stuck when using kubernets to install zulip. I will briefly state my use case and problem. 

## use case
my use case is to set up zulip server in a cluster without internet, the reason is the company's security issue. The company requires us to use kubernetes, so i choose to install it with kubernetes. The kubernetes I use is minikube.

## installation 
1. git clone https://github.com/zulip/docker-zulip.git
2. cd docker-zulip/kubernetes/manual
3. vim zulip-rc.yaml ,set DISABLE_HTTPS: "True" 
4. kubectl apply -f zulip-rc.yaml and wait for the installation to finish
5. kubectl exec -it <zulip-pod> -c zulip bash

## problem 
curl localhost and got the result below

![Screenshot from 2022-07-26 10-50-07](https://user-images.githubusercontent.com/36685525/180912584-253336f8-68d4-4bc3-8b68-1858ee413c33.png)

here is the content of django.log
![Screenshot from 2022-07-26 10-25-32](https://user-images.githubusercontent.com/36685525/180911171-12efabdb-7a12-4641-bf15-6ad073fe954c.png)

here is the content of error.log
```
root@zulip-1-4nvr9:/var/log/zulip# cat errors.log 
2022-07-26 02:14:26.481 WARN [zerver.lib.push_notifications] Mobile push notifications are not configured.
  See https://zulip.readthedocs.io/en/latest/production/mobile-push-notifications.html
```

then I tried to generate a link for registration and curl the link using http, but it was still 500 internal error.
![Screenshot from 2022-07-26 10-24-43](https://user-images.githubusercontent.com/36685525/180911480-69e487e0-38ee-4a38-bab3-f803029f24b3.png)

I use htop to monitor the cpu and memory usage and found all is ok
![Screenshot from 2022-07-26 10-23-19](https://user-images.githubusercontent.com/36685525/180911562-a331f60f-84ee-4f14-9c03-d8598bdb707d.png)

I have no idea how to proceed, can someone give some advise on the problem.

**Comment by timabbott** [comment]
The `django.log` errors suggest that the Django processes are crashing immediately on trying to process their first request. I suspect you gave the system insufficient RAM; that's usually the only way I see those Python processes crash without printing something.
