### ISSUE TITLE
DISABLE_HTTPS Problem

### ISSUE THREAD

**Issue by VannaKarenina** [zulip/docker-zulip#385]
Hi, all. I am using zulip inside docker and when set DISABLE_HTTPS = True i cant open http://localhost.

Sometimes its work but i see this

![image](https://user-images.githubusercontent.com/46137062/218525049-b60b588d-c197-497b-a07d-f2b6ccc1a146.png)

**Comment by timabbott** [comment]
This does not seem likely to reflect a problem with Zulip or this image, but instead with the configuration. Closing.
