### ISSUE TITLE
Commenting out lines in settings.py

### ISSUE THREAD

**Issue by mp-strachan** [zulip/docker-zulip#394]
Hello,

Is there anyway to remove a preference from the standard settings.py file?

I am looking at setting up S3 uploads, but the docs call for commenting out the `LOCAL_UPLOADS_DIR` key.

We use the `SETTINGS_` feature of the docker-compose file to dynamically set all our settings, which is ideal as it allows us to use a .env file.

Is there anyway to remove the LOCAL_UPLOADS_DIR key for configuring S3, without manually providing a settings.py and zulip-secrets.conf file?

Cheers!
Matt

**Comment by ympek** [comment]
Hello, we have encountered the same issue in our setup and resolved it.
Here is a trick to achieve this - the entrypoint script accepts `ZULIP_CUSTOM_SETTINGS` environment variable, which contents will be appended to the `settings.py` file. Any valid python will do, so just unset the variable here using `del`:

```
ZULIP_CUSTOM_SETTINGS: "del LOCAL_UPLOADS_DIR"
```

Hope it helps!

BR,
ympek

**Comment by timabbott** [comment]
I think `LOCAL_UPLOADS_DIR = None` would also work, without doing the `del`. But I'll look at just making it default differently in zulip/zulip, thanks for the reports.

**Comment by timabbott** [comment]
Started https://chat.zulip.org/#narrow/stream/3-backend/topic/LOCAL_UPLOADS_DIR.20defaults/near/1949118.

**Comment by timabbott** [comment]
I think the answer here is that this indeeds needs to be set as `LOCAL_UPLOADS_DIR = None`. So probably we should document that.
