### ISSUE TITLE
Error 429 when trying to create an organization after install

### ISSUE THREAD

**Issue by acasanova99** [zulip/docker-zulip#398]
I have explained the issue here: https://chat.zulip.org/#narrow/stream/31-production-help/topic/.E2.9C.94.20Error.20429.20.28Too.20Many.20Request.29.20After.20creating.20the.20first.20o.2E.2E.2E.

I have already solve the issue but I think that it would be interesting to add the following environment variable to the `zulip` container, just to avoid this error.

RATE_LIMITING_RULES='{"api_by_ip":[(60, 100),],}'

**Comment by timabbott** [comment]
I would expect that `SETTING_RATE_LIMITING_RULES` would work for adding such a rate limit.

Reading the chat.zulip.org thread, it's not obvious to me that there's any bug in this project; I think that content is present by default. But it would be great if you can contribute the podman port that you were working on there. Thanks @acasanova99!
