### ISSUE TITLE
OIDC Redirect URI incorrect behind reverse proxy

### ISSUE THREAD

**Issue by mp-strachan** [zulip/docker-zulip#404]
After an upgrade to Zulip 7.0, the redirect URI is now being passed to the IdP as "http://" rather than "https://", so our OIDC (which requires using HTTPS) throws back an error. `DISABLE_HTTPS:` is set to `true` in the docker-compose, as it's behind a reverse proxy.

![image](https://github.com/zulip/docker-zulip/assets/26296076/5527fc3e-454e-4438-8ed5-253570659023)

This error didn't occur in Zulip 6.... Not sure if this can be overridden in a config file?

**Comment by tomkv** [comment]
Same thing happening for SAML2: /saml/metadata.xml contains AssertionConsumerService Location="http://..." and IdP then complains about invalid redirect uri.

DISABLE_HTTPS is set to true, and reverse proxy is configured to provide X-Forwarded-Proto $schema.

**Comment by maltokyo** [comment]
Does this fix it for you? https://github.com/zulip/docker-zulip/issues/403
It was the only thing I needed to do to upgrade to 7.0

**Comment by jeehoonkang** [comment]
@maltokyo I edited CSRF settings per #403 but the OIDC redirect uri problem remains after upgrading Zulip to 7.0.

Before editing CSRF settings, the website kept refreshing.

**Comment by jeehoonkang** [comment]
I don't think it's a proper fix, but I found a workaround: adding `SETTING_SOCIAL_AUTH_REDIRECT_IS_HTTPS: 'True'` in `docker-compose.yml`.

Relevant documentation: https://python-social-auth.readthedocs.io/en/latest/configuration/settings.html

**Comment by alexmv** [comment]
The fundamental error here is the same as #403 -- `X-Forwarded-Proto` is not set, or not trusted.  Playing whack-a-mole with the other settings (`SETTING_SOCIAL_AUTH_REDIRECT_IS_HTTPS ` / `SETTING_CSRF_TRUSTED_ORIGINS `) won't be helpful if Zulip still thinks requests are coming in from an untrusted connection.

`X-Forwarded-Protocol` is incorrect, and if you can link to where that's referenced, I'd be great so I can fix it.  The rest of your `location` block should be trimmed down to match [our documentation](https://zulip.readthedocs.io/en/latest/production/deployment.html#nginx-configuration) -- the `upgrade` pieces are counterproductive, as is trying to provide `X-Real-IP`.

**Comment by alexmv** [comment]
Since it's the same underlying issue, I'm going to resolve this issue and we can continue the discussion on #403.
