### ISSUE TITLE
How to configure GitHubAuthBackend ?

### ISSUE THREAD

**Issue by mdsa3d** [zulip/docker-zulip#414]
May I ask how to configure `GitHubAuthBackend`, in terms what are the added lines of code? if possible will appreciate a working documentation on it.

**Comment by nazrul-kabir** [comment]
I think you can configure via looking into `settings.py` from the main zulip repo, as well as setting the configuration secrets ex: `SOCIAL_AUTH_GITHUB_KEY`, `SOCIAL_AUTH_GITHUB_ORG_NAME` etc in `zulip-secrets.conf`. Further details are documented in your settings.py.

**Comment by timabbott** [comment]
Yes, that's correct. You can also use the `MANUAL_CONFIGURATION` option and just provide your own `/etc/zulip/` files; passing these through Docker environment variables is a bit awkawrd.
