### ISSUE TITLE
Mails are beeing sent with wrong subdomain

### ISSUE THREAD

**Issue by bguenthner** [zulip/docker-zulip#418]
Hey there,

I have an issue with sending mails with the docker compose setup. My values are as following:

  
      SETTING_EXTERNAL_HOST: "chat-test.server.domain"
      SETTING_ZULIP_ADMINISTRATOR: "admin@server.domain"
      SETTING_EMAIL_HOST: "mail.server.domain" 
      SETTING_EMAIL_HOST_USER: "chat@server.domain"
      SETTING_EMAIL_PORT: "587"
      NOREPLY_EMAIL_ADDRESS: "chat@server.domain"
      SETTING_EMAIL_USE_SSL: "False"
      SETTING_EMAIL_USE_TLS: "True"

The sending of mails apparently works, but my mail server won't let the mail pass through because of this:

`
NOQUEUE: reject: RCPT from unknown[X.X.X.X]: 553 5.7.1 <noreply@chat-test.server.domain>: Sender address rejected: not owned by user chat@server.domain; from=<noreply@chat-test.server.domain> to=<newuser@gmail.com> proto=ESMTP helo=<xxxxxxx>
`

So the chat@server.domain is not used as sender, but Zulip somehow creates a new user to send the mails from, that does not exist on the mail server. And ofc the mail server blocks this. 

Did I miss a environment setting here? I just want Zulip to send all mails als chat@server.domain and not the noreply@chat-test.server.domain

**Comment by zbajor1** [comment]
NOREPLY_EMAIL_ADDRESS: "chat@server.domain" replace to SETTING_NOREPLY_EMAIL_ADDRESS: "chat@server.domain"

life saver for me :)

thanks dude

**Comment by bguenthner** [comment]
That worked. Thank you!

**Comment by lazyest** [comment]
Have similar issue, after registration of organization mails from: seems to change from ZULIP_ADMINISTRATOR to some other one and for me sendgrid sending is braking. Is there any way to lock mails From: field to some value independent from organization?

**Comment by timabbott** [comment]
`ADD_TOKENS_TO_NOREPLY_ADDRESS` is relevant here; see the documentation in `/etc/zulip/settings.py` for details.

https://zulip.com/development-community/ is a better place to ask this sort of question for more timely help with configuration issues.
