### ISSUE TITLE
Can't backup Zulip the way it is documented

### ISSUE THREAD

**Issue by roomcays** [zulip/docker-zulip#423]
The [official documentation](https://zulip.readthedocs.io/en/stable/production/export-and-import.html#backups) currently says:

> The Zulip server has a built-in backup tool:
> 
> ```shell
> # As the zulip user
> /home/zulip/deployments/current/manage.py backup
> # Or as root
> su zulip -c '/home/zulip/deployments/current/manage.py backup'
> ```

Unfortunately, this does not work with docker-containerized 7.5 version due to two errors:

1. `FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/postgresql/14/bin/pg_dump'`
2. broken symlinks to `uploads` and `settings/zulip-secrets.conf` in final .tar.gz file

This can be fixed by some small edits of `/home/zulip/deployments/current/zerver/management/commands/backup.py`:

```patch
--- backup.py
+++ backup.py
@@ -69,7 +69,7 @@
 
             if not options["skip_db"]:
                 pg_dump_command = [
-                    f"/usr/lib/postgresql/{major_pg_version}/bin/pg_dump",
+                    f"/usr/bin/pg_dump",
                     "--format=directory",
                     "--file=" + os.path.join(tmp, "zulip-backup", "database"),
                     "--username=" + settings.DATABASES["default"]["USER"],
@@ -129,7 +129,7 @@
                     [
                         "tar",
                         f"--directory={tmp}",
-                        "-cPzf",
+                        "-cPhzf",
                         tarball_path,
                         *transform_args,
                         "--",
```

The first is to be discussed and may take the form of `$(which pg_dump)` instead of fixed path, BUT the `{major_pg_version}` will be then lost. This, however, may not be the issue of docker-packaged deployment (I'm not sure about it).

The second one is adding `--dereference` switch to `tar` command:

> ```man
>        -h, --dereference
>              Follow symlinks; archive and dump the files they point to.
> ```

Which IMO should not have negative implications.

Whole thing might be discussed with Zulip's upstream team so the docker and "native" versions of `backup.py` could be the same.

**Comment by bao-qian** [comment]
another option to backup postgresql database using manage.py is manually install client version 14
`apt install postgresql-client-14`.
then you can run manage.py backup without problem.

but if you want to backup uploads directory, fix broken symlinks is still needed.

**Comment by bao-qian** [comment]
to fix the pg_dump dependency root cause, 
I think we can either 
1. downgrade postgresql version to 14 during zulip install
downgrade here https://github.com/zulip/docker-zulip/blob/main/Dockerfile#L71C88-L71C99 with doc here https://github.com/zulip/zulip/blob/main/docs/production/deployment.md?plain=1#L70

2. upgrade docker compose postgresql image to 16.

upgrade here https://github.com/zulip/zulip/blob/main/Dockerfile-postgresql and here https://github.com/zulip/docker-zulip/blob/main/docker-compose.yml#L14

**Comment by alexmv** [comment]
zulip/zulip#31444 is also necessary to resolve this, but I'll provide feedback on that PR.
