### ISSUE TITLE
/json/messages endpoint returns 500

### ISSUE THREAD

**Issue by Pandry** [zulip/docker-zulip#427]
Hiya! Thanks for the great work!  
I manage a Zulip server for an association and we've been using zulip since version 3 I think.  
Since the version 8 update, we had a bit of issues regarding the `/json/events` endpoint:  
<img width="726" alt="image" src="https://github.com/zulip/docker-zulip/assets/17499836/2545fa2f-feda-429e-8805-f5da674d4462">
<img width="975" alt="image" src="https://github.com/zulip/docker-zulip/assets/17499836/5d1ea646-f6a8-44b1-ad52-e92e16b3a9be">

Turned out, the issue was the nginx server inside the docker container:
`2024/01/22 21:12:43 [error] 56#56: *44354 invalid URL prefix in "localhost:9800", client: 172.18.0.2, server: , request: "DELETE /json/events HTTP/1.1", host: "zulip.*.org", referrer: "https://zulip.*.org/"`

As the issue says, the upstream misses the protocol (I assumed `http` looking around in the same file)  
The fix I found was to replace `$tornado_server` with `http://tornado` in `/etc/nginx/zulip-include/app`  

Is this an issue unique to our setup? Given the git blame I suspect so, as I tried searching for this issue and possible duplicates and I found no results  

If this is indeed an issue, the fix would be as easy as editing the [app](https://github.com/zulip/zulip/blob/60225591dcc947c61b1d13202942d86886a42839/puppet/zulip/files/nginx/zulip-include-frontend/app#L67) file, right?

**Comment by timabbott** [comment]
I don't think I've seen this issue before; sorry we missed your question. It looks like the problem likely relates to an unusual hostname, so it might be unique to your setup. https://zulip.com/development-community/ would be a better place to ask this sort of question that's likely unique to your setup.
