### ISSUE TITLE
"exec /sbin/entrypoint.sh: exec format error"

### ISSUE THREAD

**Issue by xenon154** [zulip/docker-zulip#432]
Hi, I attempted to set up Zulip using the instructions (cloning the repo and skipping production instructions), but when I run `docker-compose up` inside of the Zulip directory, it keeps giving me these errors: 

`docker-zulip_zulip_1 exited with code 1`
`zulip_1      | exec /sbin/entrypoint.sh: exec format error`

I am running the container on a Raspberry Pi 4 if that helps at all.

I did not touch any of the configuration files, and only used the commands I was told to.
I'm not really sure how to fix this, so any help would be awesome.

**Comment by fluxuat0r** [comment]
When I do `docker-compose ps` it shows `docker-zulip_zulip_1` as restarting, and it doesn't leave that state.

**Comment by hiiragizawakun** [comment]
having the same issue, using Raspberry Pi 4 too

**Comment by Onur-Cansever** [comment]
having the same issue, using Orange Pi 5 too

**Comment by lukaslangrock** [comment]
I just had the same problem, and this error usually occurs when the docker image doesn't support the used architecture. As #357 and the [dockerhub image](https://hub.docker.com/r/zulip/docker-zulip/tags) shows, there is no docker image for `arm64`.

**Comment by timabbott** [comment]
Closing as this is a duplicate of #357, thanks @lukaslangrock for explaining for others!
