### ISSUE TITLE
Using External host for dependencies in Kubernetes Helm Chart

### ISSUE THREAD

**Issue by mhkarimi1383** [zulip/docker-zulip#437]
Hi

I want to have my own Redis-HA setup with CloudNativePG for PostgreSQL
this chart does not allow us to use external host for dependencies.

Also I want to use S3 as my Storage insead of a PVC (e.g. with local storage)

**Comment by mhkarimi1383** [comment]
I will use my own Application Helm chart since this chart is not suitable for my use case

**Comment by timabbott** [comment]
While Zulip doesn't have requirements for the redis image, or does need a specific postgreSQL image in order for full-text search to work well. So I am not sure it's worth adding a feature to use a different PostgreSQL base image; one can always fork for that sort of thing.

**Comment by mhkarimi1383** [comment]
@timabbott 
I want to manage my postgres instances using CloudNativePG or redis ha chart and rabbit mq chart with HA
