### ISSUE TITLE
build failed because of timeout (curl command)

### ISSUE THREAD

**Issue by gfournel** [zulip/docker-zulip#442]
Hi guys,
I'm stuck at building step when trying to run 
scripts/setup/apt-repos/zulip/custom.sh
I've got a curl error :
`curl: (7) Failed to connect to packages.groonga.org port 443: Connection timed out`

My Ubuntu machine needs a proxy to access to internet and I don't know how to set it in my Dockerfile.

Can you help me?

Thanks in advance

**Comment by timabbott** [comment]
You could consider building your container on a network that doesn't require a proxy to access the Internet. I expect upstream Docker documentation, like https://docs.docker.com/engine/daemon/proxy/, to be what you need if you'd like to build on such a network.
