### ISSUE TITLE
Dockerfile no longer builds on Zulip `main` due to outdated Python

### ISSUE THREAD

**Issue by sevmonster** [zulip/docker-zulip#445]
Building Zulip on Ubuntu 20.04LTS (focal) [fails](https://github.com/zulip/zulip/blob/6af748fa774fe381def42ec946ef0d73f24e71ae/tools/provision#L36) when using the `main` branch, as [the latest version of Python available is 3.8](https://packages.ubuntu.com/search?keywords=python3&searchon=names&exact=1&suite=all&section=all). Should it be updated to at least 22.04LTS (jammy) on `main` here before next Zulip release or in tandem with it?

If the answer is to wait, at least this post should hopefully help anyone also wondering why their bleeding edge build is failing.

**Comment by timabbott** [comment]
Thanks for the report; we did notice this when preparing the 9.0 release, but it might be nice if we'd had CI for running the `main` branch of `zulip/zulip` in Docker to encourage doing those updates more preemtively.
