### ISSUE TITLE
issue with searching

### ISSUE THREAD

**Issue by ATHENA12D** [zulip/docker-zulip#446]
Hi, i have same this issue: i deployed the zulip server in docker and use a remote postgresql, when i restore the backup of db from the old serevr to the new remote db, i faced an issue with searching, when i search on any thing there is no result, but when i search on number like "360" is search is working with numbers, i can't understand where is the issue?

_Originally posted by @ATHENA12D in https://github.com/zulip/zulip/issues/12206#issuecomment-2120015819_

**Comment by timabbott** [comment]
Try running `/home/zulip/deployments/current/scripts/setup/reindex-textual-data --force`. If you change the libc version used by PostgreSQL, which it sounds like you might have, that can correct the full-text-search indexes, which is what that symptom sounds like.
