### ISSUE TITLE
Helm Chart Dependencies and Helm Repository

### ISSUE THREAD

**Issue by B3nBeng** [zulip/docker-zulip#448]
Hello,

The dependencies of the current Helm chart are outdated and no longer accessible on Bitnami. As a result, the Helm chart is unusable because the dependencies cannot be retrieved.

Furthermore, it would be highly beneficial to host the Helm chart on a repository (OCI ?) as it would simplify the process of retrieving and updating Zulip.

Thanks you !

**Comment by jamilrshaikh** [comment]
Based on the current version please update the dependencies
`dependencies:
  - name: memcached
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - memcached
    version: 7.4.8
  - name: rabbitmq
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - rabbitmq
    version: 14.5.0
  - name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - redis
    version: 19.6.2
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - postgresql
    version: 15.5.17`

**Comment by timabbott** [comment]
I believe all the dependencies are now updated, thanks to @mikkeschiren. We can do a separate issue for a Helm repository; I don't have much personal experience, so a recommendation for how to do it would be appreciated on such an issue.
