### ISSUE TITLE
Error: Operation not permitted @ rb_check_realpath_internal...

### ISSUE THREAD

**Issue by simseb** [zulip/docker-zulip#452]
Trying to upgrade Zulip container image from 8.4-0 to 9.0-0:

```
zulip_1      | Prepared and linked the uploads directory.
zulip_1      | Executing puppet configuration ...
zulip_1      | Error: Operation not permitted @ rb_check_realpath_internal - /usr/lib/ruby/vendor_ruby/puppet/pops/loader/../../.. on node da2a22c12133.domain.local
zulip_zulip_1 exited with code 2
```
Haven't had any problem upgrading since version 6...

**Comment by amoldabade7** [comment]
Agree, facing the same issue.

**Comment by amoldabade7** [comment]
https://github.com/zulip/docker-zulip/blob/main/Dockerfile#L5
```
FROM ubuntu:22.04 as base
```
Should be changed to 

```
FROM ubuntu:24.04 as base
```
and fresh image is required to be built to start using version 9+

**Comment by timabbott** [comment]
Yes, this was fixed by updating the images for Zulip 9.x. Thanks for the reports.
