### ISSUE TITLE
About DISABLE_HTTPS

### ISSUE THREAD

**Issue by zhaojing1987** [zulip/docker-zulip#458]
I am using Docker Compose to install Zulip. In the absence of a domain name and only an IP address, I set DISABLEHTTPS to "True". However, when I access the page through IP, there is a problem. I found that when loading JS, it is using HTTPS, which causes CORS to malfunction。

![image](https://github.com/user-attachments/assets/dbc9d358-3155-400f-ba13-ff38363839e4)

Is it necessary to execute commands inside the container when creating an organization? The new organization link on the page doesn't seem very friendly, is there any way?

**Comment by timabbott** [comment]
Yeah, that would be my recommendation as well. Thanks @markc-versa for helping answer questions here.

I should also mention that Zulip does expect to have an actual hostname for the server; I wouldn't recommend deploying with just an IP address unless you have a very good reason to do that and are willing to do some fiddling to get it working.
