### ISSUE TITLE
Some updates for the helm chart

### ISSUE THREAD

**Issue by mikkeschiren** [zulip/docker-zulip#463]
Bitnami has moved to use OCI registry, also updated the versions of the charts (tested with Zulip): 
https://github.com/zulip/docker-zulip/pull/462

Some cosmetica:
Fix the link output from helm install (/upgrade):
https://github.com/zulip/docker-zulip/pull/460

Add storageclass in values (already in template):
https://github.com/zulip/docker-zulip/pull/461

**Comment by timabbott** [comment]
Closing, as most of these are done and the remaining one can be tracked at https://github.com/zulip/docker-zulip/pull/461. Thanks @mikkeschiren!
